# Generated by Django 3.2.13 on 2022-06-24 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("pages", "0001_initial"),
        ("contributions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contribution",
            name="donation_page",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="pages.donationpage"),
        ),
    ]
