# Generated by Django 3.2 on 2021-05-06 15:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0006_auto_20210504_1827"),
        ("organizations", "0003_auto_20210506_1558"),
        ("contributions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contributor",
            name="created",
            field=model_utils.fields.AutoCreatedField(
                db_index=True,
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="created",
            ),
        ),
        migrations.AddField(
            model_name="contributor",
            name="modified",
            field=model_utils.fields.AutoLastModifiedField(
                db_index=True,
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="modified",
            ),
        ),
        migrations.CreateModel(
            name="Contribution",
            fields=[
                (
                    "id",
                    models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("amount", models.IntegerField(help_text="Stored in cents")),
                ("currency", models.CharField(default="usd", max_length=3)),
                ("is_quarantined", models.BooleanField(default=False)),
                ("payment_provider_data", models.JSONField(null=True)),
                ("provider_payment_id", models.CharField(max_length=255)),
                (
                    "payment_state",
                    models.CharField(
                        choices=[
                            ("processing", "processing"),
                            ("paid", "paid"),
                            ("canceled", "canceled"),
                            ("failed", "failed"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "contributor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contributions.contributor",
                    ),
                ),
                (
                    "donation_page",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="pages.donationpage",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
            },
        ),
    ]
