# Generated by Django 3.2.14 on 2022-07-08 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0002_DEV-2030_rp_deletion_cascades_to_template_and_page"),
        ("contributions", "0002_contribution_donation_page"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contribution",
            name="donation_page",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to="pages.donationpage"),
        ),
    ]
