# Generated by Django 3.2 on 2021-05-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contributions", "0002_auto_20210506_1558"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contribution",
            old_name="is_quarantined",
            new_name="is_flagged",
        ),
        migrations.AddField(
            model_name="contribution",
            name="bad_actor_score",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="contribution",
            name="reason",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
