# Generated by Django 3.2.2 on 2021-05-14 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contributions", "0003_auto_20210514_1217"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contribution",
            name="is_flagged",
        ),
        migrations.AddField(
            model_name="contribution",
            name="bad_actor_response",
            field=models.JSONField(null=True),
        ),
    ]
