# Generated by Django 3.2.13 on 2022-07-04 21:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contributions", "0003_DEV-2030_alter_contribution_donation_page"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contribution",
            name="status",
            field=models.CharField(
                choices=[
                    ("processing", "processing"),
                    ("paid", "paid"),
                    ("canceled", "canceled"),
                    ("failed", "failed"),
                    ("flagged", "flagged"),
                    ("rejected", "rejected"),
                    ("refunded", "refunded"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
