# Generated by Django 3.2.2 on 2021-05-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contributions", "0004_auto_20210514_2023"),
    ]

    operations = [
        migrations.AddField(
            model_name="contribution",
            name="payment_provider_used",
            field=models.CharField(default="Stripe", max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="contribution",
            name="payment_state",
            field=models.CharField(
                choices=[
                    ("processing", "processing"),
                    ("paid", "paid"),
                    ("canceled", "canceled"),
                    ("failed", "failed"),
                    ("flagged", "flagged"),
                    ("rejected", "rejected"),
                ],
                max_length=10,
            ),
        ),
    ]
