# Generated by Django 3.2.2 on 2021-05-17 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contributions", "0005_auto_20210517_1435"),
    ]

    operations = [
        migrations.AddField(
            model_name="contribution",
            name="flagged_date",
            field=models.DateTimeField(null=True),
        ),
    ]
