# Generated by Django 3.2.16 on 2022-11-04 04:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("contributions", "0005_DEV-2183_contribution_provider_client_secret_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contribution",
            name="bad_actor_score",
            field=models.IntegerField(
                choices=[
                    (0, "0 - Information"),
                    (1, "1 - Unknown"),
                    (2, "2 - Good"),
                    (3, "3 - Suspect"),
                    (4, "4 - Bad"),
                    (5, "5 - Very Bad"),
                ],
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="contribution",
            constraint=models.CheckConstraint(
                check=models.Q(("bad_actor_score__in", [0, 1, 2, 3, 4, 5])),
                name="contributions_contribution_bad_actor_score_valid",
            ),
        ),
        migrations.RemoveField(
            model_name="contribution",
            name="provider_client_secret_id",
        ),
        migrations.AddField(
            model_name="contribution",
            name="provider_setup_intent_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="contribution",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
