# Generated by Django 3.2.22 on 2023-10-23 18:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ("contributions", "0006_DEV-2342_contribution_changes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        db_index=True, default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        db_index=True, default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("net_amount_paid", models.IntegerField()),
                ("gross_amount_paid", models.IntegerField()),
                ("amount_refunded", models.IntegerField()),
                ("stripe_event_id", models.CharField(max_length=255, unique=True)),
                ("stripe_charge_id", models.CharField(max_length=255)),
                ("stripe_balance_transaction_id", models.CharField(max_length=255)),
                (
                    "contribution_id",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contributions.contributor"),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["contribution_id"], name="contributio_contrib_7e2790_idx"),
        ),
    ]
