# Generated by Django 3.2.16 on 2022-11-03 18:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("contributions", "0006_DEV-2342_contribution_status_choices"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contribution",
            name="provider_client_secret_id",
        ),
        migrations.AddField(
            model_name="contribution",
            name="provider_setup_intent_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="contribution",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
