# Generated by Django 3.2.2 on 2021-06-08 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contributions", "0007_auto_20210517_1852"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contribution",
            name="payment_state",
        ),
        migrations.RemoveField(
            model_name="contribution",
            name="provider_reference_id",
        ),
        migrations.AddField(
            model_name="contribution",
            name="interval",
            field=models.CharField(
                choices=[("one_time", "One time"), ("month", "Monthly"), ("year", "Yearly")],
                default="one-time",
                max_length=8,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contribution",
            name="last_payment_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="contribution",
            name="last_payment_status",
            field=models.CharField(
                choices=[("succeeded", "Succeeded"), ("failed", "Failed")], max_length=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="contribution",
            name="provider_customer_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="contribution",
            name="provider_payment_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="contribution",
            name="provider_payment_method_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="contribution",
            name="status",
            field=models.CharField(
                choices=[
                    ("processing", "processing"),
                    ("paid", "paid"),
                    ("canceled", "canceled"),
                    ("failed", "failed"),
                    ("flagged", "flagged"),
                    ("rejected", "rejected"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
