# Generated by Django 3.2.23 on 2023-12-05 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contributions", "0007_DEV-4043_payment_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="stripe_refund_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
