# Generated by Django 3.2.23 on 2023-12-08 00:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ("contributions", "0007_DEV-4043_payment_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="transaction_time",
            field=models.DateTimeField(default=datetime.datetime(1973, 12, 20, 0, 25, 9, 216868, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
