# Generated by Django 3.2.23 on 2024-01-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contributions", "0007_DEV-4043_payment_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="transaction_time",
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
