# Generated by Django 3.2.2 on 2021-05-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contributions", "0007_auto_20210517_1852"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contribution",
            old_name="provider_payment_id",
            new_name="provider_payment_id",
        ),
        migrations.AddField(
            model_name="contribution",
            name="provider_customer_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="contribution",
            name="provider_payment_method_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="contribution",
            name="payment_state",
            field=models.CharField(
                choices=[
                    ("processing", "processing"),
                    ("paid", "paid"),
                    ("canceled", "canceled"),
                    ("failed", "failed"),
                    ("flagged", "flagged"),
                    ("rejected", "rejected"),
                    ("active", "Active"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="contributor",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
