# Generated by Django 3.2.24 on 2024-02-28 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0023_DEV-4264_create_social_meta_for_existing_rps"),
        ("contributions", "0008_DEV-4032_payment_transaction_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="contribution",
            name="revenue_program",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="organizations.revenueprogram"
            ),
        ),
    ]
