# Generated by Django 3.2.23 on 2024-01-04 16:03

from django.db import migrations

import stripe


def set_transaction_time(apps, schema_editor):
    Payment = apps.get_model("contributions", "Payment")
    for payment in Payment.objects.filter(transaction_time__isnull=True):
        bt = stripe.BalanceTransaction.retrieve(
            payment.stripe_balance_transaction_id, stripe_account=payment.contribution.stripe_account_id
        )
        payment.transaction_time = bt.created
        payment.save(update_fields={"modified", "transaction_time"})


class Migration(migrations.Migration):
    dependencies = [
        ("contributions", "0008_DEV-4032_payment_transaction_time"),
    ]
    operations = [
        migrations.RunPython(set_transaction_time),
    ]
