# Generated by Django 3.2.25 on 2024-03-26 21:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contributions", "0008_DEV-4032_payment_transaction_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contribution",
            name="interval",
            field=models.CharField(
                choices=[("one_time", "One-time"), ("month", "Monthly"), ("year", "Yearly")], max_length=8
            ),
        ),
    ]
