# Generated by Django 3.2.2 on 2021-05-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contributions", "0008_auto_20210528_1309"),
    ]

    operations = [
        migrations.AddField(
            model_name="contribution",
            name="interval",
            field=models.CharField(
                choices=[
                    ("one_time", "One time"),
                    ("day", "Daily"),
                    ("week", "Weekly"),
                    ("month", "Monthly"),
                    ("year", "Yearly"),
                ],
                default="one_time",
                max_length=8,
            ),
            preserve_default=False,
        ),
    ]
