# Generated by Django 3.2.2 on 2021-05-28 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contributions", "0009_contribution_interval"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contribution",
            name="provider_customer_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="contribution",
            name="provider_payment_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="contribution",
            name="provider_payment_method_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
