# Generated by Django 3.2.25 on 2024-05-07 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "DEV-3960_add_locale_to_page"),
        ("organizations", "0024_DEV-3870_add_contact_phone"),
        ("contributions", "0009_DEV-4603_alter_contribution_interval"),
    ]

    operations = [
        migrations.AddField(
            model_name="contribution",
            name="_revenue_program",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="organizations.revenueprogram"
            ),
        ),
        migrations.AlterField(
            model_name="contribution",
            name="donation_page",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="pages.donationpage"
            ),
        ),
        migrations.AddConstraint(
            model_name="contribution",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("_revenue_program__isnull", True), ("donation_page__isnull", False)),
                    models.Q(("_revenue_program__isnull", False), ("donation_page__isnull", True)),
                    _connector="OR",
                ),
                name="contributions_contribution_exclusive_donation_page_or__revenue_program",
            ),
        ),
    ]
