# Generated by Django 3.2.25 on 2024-04-26 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0024_DEV-3870_add_contact_phone"),
        ("contributions", "0009_DEV-4603_alter_contribution_interval"),
    ]

    operations = [
        migrations.AddField(
            model_name="contribution",
            name="_revenue_program",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="organizations.revenueprogram"
            ),
        ),
        migrations.AddConstraint(
            model_name="contribution",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        models.Q(("donation_page__isnull", False), ("_revenue_program__isnull", True)),
                        models.Q(("donation_page__isnull", True), ("_revenue_program__isnull", False)),
                        _connector="OR",
                    ),
                    models.Q(("donation_page__isnull", False), ("_revenue_program__isnull", False), _negated=True),
                ),
                name="contributions_contribution_exclusive_donation_page_or_revenue_program",
            ),
        ),
    ]
