# Generated by Django 3.2.2 on 2021-06-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contributions", "0009_remove_contribution_last_payment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contributor",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
