# Generated by Django 3.2.24 on 2024-02-28 18:49

from django.db import migrations


def add_revenue_program(apps, schema_editor):
    Contribution = apps.get_model("contributions", "Contribution")
    for x in Contribution.objects.filter(revenue_program_id__isnull=True, donation_page__revenue_program__isnull=False):
        x.revenue_program_id = x.donation_page.revenue_program.id
        x.save(update_fields={"revenue_program_id", "modified"})


class Migration(migrations.Migration):

    dependencies = [
        ("contributions", "0009_DEV-4507_contribution_revenue_program"),
    ]

    operations = [
        migrations.RunPython(add_revenue_program, reverse_code=migrations.RunPython.noop),
    ]
