# Generated by Django 3.2.2 on 2021-06-29 13:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("contributions", "0010_alter_contributor_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="contributor",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
