# Generated by Django 3.2.24 on 2024-02-28 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0023_DEV-4264_create_social_meta_for_existing_rps"),
        ("contributions", "0010_DEV-4507_migrate_revenue_program"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contribution",
            name="revenue_program",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="organizations.revenueprogram"),
        ),
    ]
