# Generated by Django 3.2.2 on 2021-06-01 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contributions", "0010_auto_20210528_2016"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contribution",
            name="interval",
            field=models.CharField(
                choices=[("one_time", "One time"), ("month", "Monthly"), ("year", "Yearly")], max_length=8
            ),
        ),
    ]
