# Generated by Django 3.2.25 on 2024-05-15 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contributions", "0010_DEV-4562_add_revenue_program_with_constraint"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contribution",
            name="provider_payment_method_details",
        ),
    ]
