# Generated by Django 3.2.2 on 2021-06-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contributions", "0011_alter_contribution_interval"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contribution",
            name="payment_state",
        ),
        migrations.AddField(
            model_name="contribution",
            name="last_payment_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="contribution",
            name="last_payment_status",
            field=models.CharField(
                choices=[("succeeded", "Succeeded"), ("failed", "Failed")], max_length=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="contribution",
            name="status",
            field=models.CharField(
                choices=[
                    ("processing", "processing"),
                    ("paid", "paid"),
                    ("canceled", "canceled"),
                    ("failed", "failed"),
                    ("flagged", "flagged"),
                    ("rejected", "rejected"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
