# Generated by Django 3.2.2 on 2021-07-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contributions", "0011_contributor_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="contribution",
            name="provider_payment_method_details",
            field=models.JSONField(null=True),
        ),
    ]
