# Generated by Django 3.2.2 on 2021-07-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contributions", "0012_contribution_provider_payment_method_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="contribution",
            name="provider_subscription_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
