# Generated by Django 4.2.15 on 2024-09-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contributions", "0013_DEV-5173_remove_contribution_first_payment_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contribution",
            name="provider_subscription_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
