# Generated by Django 3.2.5 on 2021-07-16 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contributions", "0012_contributionmetadata"),
        ("contributions", "0013_contribution_provider_subscription_id"),
    ]

    operations = []
