# Generated by Django 3.2.5 on 2021-07-16 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contributions", "0014_merge_20210716_1852"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contributionmetadata",
            name="donor_supplied",
            field=models.BooleanField(
                default=False,
                help_text="If on, this field will be available for Org Admins to add to a donation page. If off, this field will not be visible on the front end.",
            ),
        ),
    ]
