# Generated by Django 3.2.5 on 2021-07-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contributions", "0015_alter_contributionmetadata_donor_supplied"),
    ]

    operations = [
        migrations.AddField(
            model_name="contribution",
            name="contribution_metadata",
            field=models.JSONField(null=True),
        ),
    ]
