# Generated by Django 4.2.16 on 2024-11-26 16:44

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contributions", "0015_DEV-5494_data_migration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contributor",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AddConstraint(
            model_name="contributor",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("email"), name="unique_email_lower"
            ),
        ),
    ]
