# Generated by Django 4.2.18 on 2025-02-07 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contributions", "0016_DEV-5725_contributor_email_future"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="transaction_time",
            field=models.DateTimeField(db_index=False),
        ),
    ]
