# Generated by Django 3.2.5 on 2021-08-20 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contributions", "0016_contribution_contribution_metadata"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contribution",
            options={"get_latest_by": "modified", "ordering": ["-created"]},
        ),
    ]
