# Generated by Django 3.2.5 on 2021-10-29 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contributions", "0017_alter_contribution_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ContributionMetadata",
        ),
    ]
