# Generated by Django 4.2.19 on 2025-04-23 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contributions", "0017_DEV-5523_alter_payment_transaction_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="contribution",
            name="quarantine_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("flagged_by_bad_actor", "Flagged by bad actor"),
                    ("rejected_by_human_for_fraud", "Rejected by human for being fraudulent"),
                    ("rejected_by_human_for_dupe", "Rejected by human for being a duplicate"),
                    ("rejected_by_human_for_other", "Rejected by human for some other reason"),
                    ("rejected_by_machine_for_bad_actor", "Rejected by machine for being a bad actor"),
                    ("approved_by_machine_after_wait", "Approved by machine after waiting"),
                    ("approved_by_human", "Approved by human"),
                    ("rejected_by_stripe_for_fraud", "Rejected by Stripe for being fraudulent"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
