# Generated by Django 4.2.20 on 2025-05-12 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contributions", "0018_DEV-5353_contribution_quarantine_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contribution",
            name="contributor",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="contributions.contributor"),
        ),
    ]
