# Generated by Django 4.2.20 on 2025-05-12 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contributions", "0018_DEV-5353_contribution_quarantine_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contribution",
            name="contributor",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="contributions.contributor"),
        ),
        # Step 1: Add CHECK constraint with NOT VALID (non-blocking)
        migrations.RunSQL(
            sql="ALTER TABLE contributions_contribution ADD CONSTRAINT contributor_id_not_null CHECK (contributor_id IS NOT NULL) NOT VALID;",
            reverse_sql="ALTER TABLE contributions_contribution DROP CONSTRAINT contributor_id_not_null;",
        ),
        # Step 2: Validate the constraint (reads table but doesn't block writes)
        migrations.RunSQL(
            sql="ALTER TABLE contributions_contribution VALIDATE CONSTRAINT contributor_id_not_null;",
            reverse_sql="",
        ),
        # Step 3: Convert to proper NOT NULL constraint (quick operation since data is validated)
        migrations.RunSQL(
            sql="ALTER TABLE contributions_contribution ALTER COLUMN contributor_id SET NOT NULL;",
            reverse_sql="ALTER TABLE contributions_contribution ALTER COLUMN contributor_id DROP NOT NULL;",
        ),
        # Step 4: Clean up the check constraint (no longer needed)
        migrations.RunSQL(
            sql="ALTER TABLE contributions_contribution DROP CONSTRAINT contributor_id_not_null;",
            reverse_sql="ALTER TABLE contributions_contribution ADD CONSTRAINT contributor_id_not_null CHECK (contributor_id IS NOT NULL);",
        ),
    ]
