# Generated by Django 4.2.21 on 2025-07-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contributions", "0019_DEV-5953_alter_contribution_contributor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contribution",
            name="quarantine_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("flagged_by_bad_actor", "Flagged by bad actor"),
                    ("rejected_by_human_for_fraud", "Rejected by human for being fraudulent"),
                    ("rejected_by_human_for_dupe", "Rejected by human for being a duplicate"),
                    ("rejected_by_human_for_other", "Rejected by human for some other reason"),
                    ("rejected_by_machine_for_bad_actor", "Rejected by machine for being a bad actor"),
                    ("approved_by_machine_after_wait", "Approved by machine after waiting"),
                    ("approved_by_human", "Approved by human"),
                    ("rejected_by_stripe_for_fraud", "Rejected by Stripe for being fraudulent"),
                    ("rejected_by_human_for_unknown", "Rejected by human for unknown reason"),
                    ("approved_by_unknown", "Approved by unknown"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
