# Generated by Django 4.2.23 on 2025-07-30 17:57

import django.db.models.functions.text
from django.contrib.postgres.operations import CreateCollation
from django.db import migrations, models


def copy_email_future_to_email_ci_deterministic(apps, schema_editor):
    Contributor = apps.get_model("contributions", "Contributor")
    for contributor in Contributor.objects.all():
        if contributor.email_future:
            contributor.email_ci_deterministic = contributor.email_future
            contributor.save(update_fields=["email_ci_deterministic"])


class Migration(migrations.Migration):

    dependencies = [
        ("contributions", "0020_DEV-5528_alter_contribution_quarantine_status"),
    ]

    operations = [
        CreateCollation("ci_deterministic", provider="icu", locale="und-u-ks-level2", deterministic=True),
        migrations.AddField(
            model_name="contributor",
            name="email_ci_deterministic",
            field=models.EmailField(
                blank=True,
                db_collation="ci_deterministic",
                help_text="Case insensitive email",
                max_length=254,
                null=True,
                unique=True,
            ),
        ),
        migrations.RunPython(copy_email_future_to_email_ci_deterministic, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="contributor",
            name="email",
        ),
        migrations.RemoveField(
            model_name="contributor",
            name="email_future",
        ),
        migrations.RenameField(
            model_name="contributor",
            old_name="email_ci_deterministic",
            new_name="email",
        ),
        migrations.AlterField(
            model_name="contributor",
            name="email",
            field=models.EmailField(
                blank=False, null=False, unique=True, db_collation="ci_deterministic", max_length=254
            ),
        ),
        migrations.AddConstraint(
            model_name="contributor",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("email"), name="unique_email_case_insensitive"
            ),
        ),
    ]
