# Generated by Django 3.2.5 on 2022-05-09 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contributions", "0020_initial_historical_record"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contribution",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="historicalcontribution",
            name="organization",
        ),
    ]
