# Generated by Django 4.2.13 on 2024-06-06 20:56

from django.contrib.postgres.operations import CreateCollation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contributions", "0020_DEV-5528_alter_contribution_quarantine_status"),
    ]

    operations = [
        CreateCollation("case_insensitive_deterministic", provider="icu", locale="und-u-ks-level2", deterministic=True),
        migrations.AddField(
            model_name="contributor",
            name="email_insensitive",
            field=models.EmailField(
                blank=True, db_collation="case_insensitive_deterministic", max_length=254, null=True, unique=True
            ),
        ),
    ]
