# Generated by Django 4.2.23 on 2025-07-18 14:44

from django.contrib.postgres.operations import CreateCollation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contributions", "0020_DEV-5528_alter_contribution_quarantine_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contributor",
            name="email",
        ),
        migrations.RenameField(
            model_name="contributor",
            old_name="email_future",
            new_name="email",
        ),
        CreateCollation(
            "case_insensitive_future",
            provider="icu",
            locale="und-u-ks-level2",
            deterministic=True,
        ),
        migrations.AlterField(
            model_name="contributor",
            name="email",
            field=models.EmailField(blank=False, null=False, unique=True, db_collation="case_insensitive_future"),
        ),
    ]
