# Generated by Django 4.2.23 on 2025-07-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contributions", "0020_DEV-5528_alter_contribution_quarantine_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contributor",
            name="email",
        ),
        migrations.RenameField(
            model_name="contributor",
            old_name="email_future",
            new_name="email",
        ),
        migrations.AlterField(
            model_name="contributor",
            name="email",
            field=models.EmailField(
                blank=False, null=False, unique=True, db_collation="case_insensitive", max_length=254
            ),
        ),
    ]
