# Generated by Django 3.2.13 on 2022-06-17 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contributions", "0021_associate_stripe_with_rp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalcontributor",
            name="history_user",
        ),
        migrations.DeleteModel(
            name="HistoricalContribution",
        ),
        migrations.DeleteModel(
            name="HistoricalContributor",
        ),
    ]
