# Generated by Django 3.2.5 on 2022-01-28 14:23

from django.contrib.postgres.operations import CITextExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = []

    operations = [CITextExtension()]
