# Generated by Django 3.2.5 on 2022-01-28 14:33

import django.contrib.postgres.fields.citext
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("config", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DenyListWord",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("word", django.contrib.postgres.fields.citext.CICharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Deny-list word",
                "verbose_name_plural": "Deny-list words",
            },
        ),
    ]
