# Generated by Django 3.2.25 on 2024-05-23 20:10

import django.contrib.postgres.operations
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("config", "0003_DEV-4761_add_case_insensitive_collation"),
        ("config", "0004_DEV-4761_alter_denylistword_word"),
    ]

    dependencies = [
        ("config", "0002_denylistword"),
    ]

    operations = [
        django.contrib.postgres.operations.CreateCollation(
            name="case_insensitive",
            locale="und-u-ks-level2",
        ),
        migrations.AlterField(
            model_name="denylistword",
            name="word",
            field=models.TextField(db_collation="case_insensitive", max_length=255, unique=True),
        ),
    ]
