# Generated by Django 4.2.10 on 2024-03-01 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0002_denylistword"),
    ]

    operations = [
        migrations.AlterField(
            model_name="denylistword",
            name="word",
            field=models.CharField(db_collation="english_ci", max_length=255, unique=True),
        ),
    ]


# CREATE COLLATION english_ci (
#    PROVIDER = 'icu',
#    LOCALE = 'en-US@colStrength=secondary',
#    DETERMINISTIC = FALSE
# );
