# Generated by Django 4.2.13 on 2024-06-06 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0002_denylistword"),
    ]

    operations = [
        migrations.AlterField(
            model_name="denylistword",
            name="word",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddConstraint(
            model_name="denylistword",
            constraint=models.UniqueConstraint(
                models.functions.text.Lower("word"), name="word_unique_case_insensitive"
            ),
        ),
    ]
