# Generated by Django 4.2.13 on 2024-06-06 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0003_DEV-4110_add_case_insensitive_collation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="denylistword",
            name="word",
            field=models.CharField(db_collation="case_insensitive", max_length=255, unique=True),
        ),
    ]
