# Generated by Django 3.2.25 on 2024-05-15 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0003_DEV-4761_add_case_insensitive_collation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="denylistword",
            name="word",
            field=models.CharField(db_collation="case_insensitive", max_length=255, unique=True),
        ),
    ]
