import os


ENVIRONMENT = os.environ["ENVIRONMENT"]
DOMAIN = os.environ["DOMAIN"]
STANDING_NAMES = ("test", "staging", "sandbox", "dev", "demo")
DEFAULT_CHECKOUT_URL = f"https://billypenn{f'-{ENVIRONMENT}' if ENVIRONMENT not in STANDING_NAMES else ''}.{DOMAIN}"
CHECKOUT_PAGE_URL = os.environ.get("CHECKOUT_PAGE_URL", DEFAULT_CHECKOUT_URL)
STRIPE_API_KEY = os.environ["STRIPE_API_KEY"]
VISA = "4242424242424242"
MASTER_CARD = "5555555555554444"
REVENUE_PROGRAM_NAME = "Billy Penn"

DATABASE_URL = os.environ["DATABASE_URL"]
