# Generated by Django 3.2.2 on 2021-07-02 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0017_auto_20210617_1533"),
    ]

    operations = [
        migrations.CreateModel(
            name="HubSlackIntegration",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("bot_token", models.CharField(max_length=255)),
                (
                    "channel",
                    models.CharField(
                        help_text="All donation notifications will be sent to this channel", max_length=255
                    ),
                ),
                (
                    "org_channel_prefix",
                    models.CharField(
                        default="donations-",
                        help_text="Donation notifications will be sent to [org-channel-prefix][recipient-org-name]",
                        max_length=24,
                    ),
                ),
            ],
            options={
                "verbose_name": "[News Revenue Hub] Slack integration config",
            },
        ),
        migrations.CreateModel(
            name="OrganizationSlackIntegration",
            fields=[
                ("bot_token", models.CharField(max_length=255)),
                (
                    "channel",
                    models.CharField(
                        help_text="All donation notifications will be sent to this channel", max_length=255
                    ),
                ),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="slack_integration",
                        serialize=False,
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
