# Generated by Django 3.2.16 on 2022-10-20 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("slack", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hubslackintegration",
            name="channel",
            field=models.CharField(
                help_text="All contribution notifications will be sent to this channel", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="hubslackintegration",
            name="org_channel_prefix",
            field=models.CharField(
                default="#contribution-",
                help_text="Contribution notifications will be sent to [org-channel-prefix][recipient-org-name]",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="organizationslackintegration",
            name="channel",
            field=models.CharField(
                help_text="All contribution notifications will be sent to this channel", max_length=255
            ),
        ),
    ]
