# Generated by Django 3.2.5 on 2021-07-07 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("slack", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hubslackintegration",
            name="org_channel_prefix",
            field=models.CharField(
                default="#donations-",
                help_text="Donation notifications will be sent to [org-channel-prefix][recipient-org-name]",
                max_length=24,
            ),
        ),
    ]
