# Generated by Django 3.2.16 on 2022-12-20 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("slack", "0002_DEV-1446_rename_donation_in_help_text_and_slack_channel"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HubSlackIntegration",
        ),
        migrations.DeleteModel(
            name="OrganizationSlackIntegration",
        ),
    ]
