# Generated by Django 3.2.14 on 2022-07-08 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0004_DEV-2049_delete_address_fks"),
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Address",
        ),
    ]
