# Generated by Django 3.2.14 on 2022-07-08 04:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0004_DEV-2049_add_org_country_retire_address"),
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Address",
        ),
    ]
