# Generated by Django 3.2.5 on 2021-09-08 12:07

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialMeta",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(blank=True, max_length=95)),
                ("description", models.TextField(blank=True)),
                ("url", models.URLField(blank=True)),
                ("card", sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to="")),
            ],
        ),
    ]
