# Generated by Django 3.2.14 on 2022-07-08 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0006_DEV-2049_drop_address_from_rp_and_org"),
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Address",
        ),
    ]
