# Generated by Django 3.2.5 on 2021-10-04 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_socialmeta"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="country",
            field=models.CharField(
                blank=True,
                choices=[("USA", "USA"), ("CAN", "CAN")],
                default="USA",
                max_length=3,
                verbose_name="Country",
            ),
        ),
    ]
