# Generated by Django 3.2.5 on 2021-10-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_socialmeta"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="country",
            field=models.CharField(
                blank=True, choices=[("US", "US"), ("CA", "CA")], default="US", max_length=2, verbose_name="Country"
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AL", "Alabama"),
                    ("AK", "Alaska"),
                    ("AZ", "Arizona"),
                    ("AR", "Arkansas"),
                    ("CA", "California"),
                    ("CO", "Colorado"),
                    ("CT", "Connecticut"),
                    ("DC", "Washington D.C."),
                    ("DE", "Delaware"),
                    ("FL", "Florida"),
                    ("GA", "Georgia"),
                    ("HI", "Hawaii"),
                    ("ID", "Idaho"),
                    ("IL", "Illinois"),
                    ("IN", "Indiana"),
                    ("IA", "Iowa"),
                    ("KS", "Kansas"),
                    ("LA", "Louisiana"),
                    ("ME", "Maine"),
                    ("MD", "Maryland"),
                    ("MA", "Massachusetts"),
                    ("MI", "Michigan"),
                    ("MN", "Minnesota"),
                    ("MS", "Mississippi"),
                    ("MO", "Missouri"),
                    ("MT", "Montana"),
                    ("NE", "Nebraska"),
                    ("NV", "Nevada"),
                    ("NH", "New Hampshire"),
                    ("NJ", "New Jersey"),
                    ("NM", "New Mexico"),
                    ("NY", "New York"),
                    ("NC", "North Carolina"),
                    ("ND", "North Dakota"),
                    ("OH", "Ohio"),
                    ("OK", "Oklahoma"),
                    ("OR", "Oregon"),
                    ("PA", "Pennsylvania"),
                    ("RI", "Rhode Island"),
                    ("SC", "South Carolina"),
                    ("SD", "South Dakota"),
                    ("TN", "Tennessee"),
                    ("TX", "Texas"),
                    ("UT", "Utah"),
                    ("VT", "Vermont"),
                    ("VA", "Virginia"),
                    ("WA", "Washington"),
                    ("WI", "Wisconsin"),
                    ("WY", "Wyoming"),
                    ("AB", "Alberta"),
                    ("BC", "British Columbia"),
                    ("MB", "Manitoba"),
                    ("NB", "New Brunswick"),
                    ("NL", "Newfoundland and Labrador"),
                    ("NS", "Nova Scotia"),
                    ("NT", "Northwest Territories"),
                    ("NU", "Nunavut"),
                    ("ON", "Ontario"),
                    ("PE", "Prince Edward Island"),
                    ("QC", "Quebec"),
                    ("SK", "Saskatchewan"),
                    ("YT", "Yukon"),
                ],
                max_length=2,
                verbose_name="State/Province",
            ),
        ),
    ]
