# Generated by Django 3.2.5 on 2022-02-08 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("common", "0003_auto_20211005_1324"),
    ]

    operations = [
        migrations.CreateModel(
            name="RevEngineHistoricalChange",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("app_label", models.CharField(max_length=40)),
                ("model", models.CharField(max_length=40)),
                ("object_id", models.PositiveSmallIntegerField()),
                ("history_date", models.DateTimeField(verbose_name="Date/Time")),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                        verbose_name="Comment",
                    ),
                ),
                ("history_change_reason", models.CharField(blank=True, max_length=255, verbose_name="Change Reason")),
                ("changes_html", models.CharField(blank=True, max_length=1000)),
                (
                    "history_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Changed By",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Historial Changes",
            },
        ),
    ]
