# Generated by Django 3.2.13 on 2022-06-15 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0004_revenginehistoricalchange"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RevEngineHistoricalChange",
        ),
    ]
