# Generated by Django 3.2.13 on 2022-06-24 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    # manually added this after renaming this migration file to be semantic, based on
    # error raised by django-test-migrations, which we're using to prohibit default
    # migration names
    replaces = [
        ("users", "0002_auto_20220624_0235"),
    ]

    dependencies = [
        ("organizations", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoleAssignment",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "role_type",
                    models.CharField(
                        choices=[("hub_admin", "Hub Admin"), ("org_admin", "Org Admin"), ("rp_admin", "RP Admin")],
                        max_length=50,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="organizations.organization",
                    ),
                ),
                ("revenue_programs", models.ManyToManyField(blank=True, to="organizations.RevenueProgram")),
                (
                    "user",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrganizationUser",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_owner", models.BooleanField(default=False)),
                (
                    "organization",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="organizations",
            field=models.ManyToManyField(through="users.OrganizationUser", to="organizations.Organization"),
        ),
    ]
