# Generated by Django 3.2.14 on 2022-07-15 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_DEV-1710_create_organization_user_and_role_assignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="accepted_terms_of_service",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="email_verified",
            field=models.BooleanField(default=False),
        ),
    ]
