# Generated by Django 3.2.5 on 2022-02-16 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0046_merge_20220203_1437"),
        ("users", "0002_auto_20210423_1718"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoleAssignment",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "role_type",
                    models.CharField(
                        choices=[("hub_admin", "Hub Admin"), ("org_admin", "Org Admin"), ("rp_admin", "RP Admin")],
                        max_length=9,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="organizations.organization",
                    ),
                ),
                ("revenue_programs", models.ManyToManyField(blank=True, to="organizations.RevenueProgram")),
                (
                    "user",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
    ]
