# Generated by Django 3.2.5 on 2022-03-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_roleassignment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roleassignment",
            name="role_type",
            field=models.CharField(
                choices=[("hub_admin", "Hub Admin"), ("org_admin", "Org Admin"), ("rp_admin", "RP Admin")],
                max_length=50,
            ),
        ),
    ]
