# Generated by Django 3.2.14 on 2022-07-15 18:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_DEV-2030_alter_roleassignment_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="accepted_terms_of_service",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="email_verified",
            field=models.BooleanField(default=False),
        ),
    ]
