# Generated by Django 3.2.18 on 2023-03-28 14:02

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_DEV-2644_alter_user_accepted_terms_of_service"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=255, unique=True, validators=[apps.users.models.case_insensitive_unique_username_validator]
            ),
        ),
    ]
