# Generated by Django 4.2.15 on 2024-09-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_DEV-3909_alter_roleassignment_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="test_field",
            field=models.CharField(null=True),
        ),
    ]
