# Generated by Django 4.2.21 on 2025-07-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activity_log", "0001_DEV-5825_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylog",
            name="action",
            field=models.CharField(choices=[("cancel", "canceled"), ("send_receipt", "sent receipt")], max_length=255),
        ),
    ]
