# Generated by Django 3.2.5 on 2021-07-28 16:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pages", "0022_donationpage_deleted"),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        db_index=True, default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        db_index=True, default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("spa_key", models.UUIDField(blank=True)),
                ("height", models.PositiveIntegerField()),
                ("width", models.PositiveIntegerField()),
                ("image", models.ImageField(height_field="height", upload_to="images", width_field="width")),
                ("image_attrs", models.JSONField(blank=True)),
                ("page_id", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="pages.donationpage")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
