# Generated by Django 3.2.5 on 2021-08-10 17:11

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediaimage",
            name="image",
            field=sorl.thumbnail.fields.ImageField(height_field="height", upload_to="images", width_field="width"),
        ),
    ]
