# Generated by Django 3.2.5 on 2021-08-10 20:04

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0002_alter_mediaimage_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediaimage",
            name="thumb",
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to="images/thumbs"),
        ),
    ]
