# Generated by Django 3.2.5 on 2021-08-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0004_auto_20210810_2020"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediaimage",
            name="image_attrs",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
