# Generated by Django 3.2 on 2021-04-22 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_bg_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('header_logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('header_link', models.URLField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('elements', models.JSONField(blank=True, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_bg_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('header_logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('header_link', models.URLField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('elements', models.JSONField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
