# Generated by Django 3.2 on 2021-04-22 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BenefitTier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('benefits', models.ManyToManyField(to='pages.Benefit')),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('styles', models.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='show_benefits',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='template',
            name='show_benefits',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='DonorBenefit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('blurb', models.TextField(blank=True, null=True)),
                ('tiers', models.ManyToManyField(to='pages.BenefitTier')),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='donor_benefits',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.donorbenefit'),
        ),
        migrations.AddField(
            model_name='page',
            name='styles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.style'),
        ),
        migrations.AddField(
            model_name='template',
            name='donor_benefits',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.donorbenefit'),
        ),
        migrations.AddField(
            model_name='template',
            name='styles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.style'),
        ),
    ]
