# Generated by Django 3.2 on 2021-04-22 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DonationPage",
            fields=[
                (
                    "id",
                    models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("header_bg_image", models.ImageField(blank=True, null=True, upload_to="")),
                ("header_logo", models.ImageField(blank=True, null=True, upload_to="")),
                ("header_link", models.URLField(blank=True, null=True)),
                ("title", models.CharField(max_length=255)),
                ("elements", models.JSONField(blank=True, null=True)),
                ("show_benefits", models.BooleanField(default=False)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("slug", models.SlugField(unique=True)),
                ("published_date", models.DateTimeField(blank=True, null=True)),
                (
                    "donor_benefits",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="pages.donorbenefit",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"),
                ),
                (
                    "revenue_program",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="organizations.revenueprogram",
                    ),
                ),
                (
                    "styles",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="pages.style",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="Page",
        ),
    ]
