# Generated by Django 3.2.16 on 2022-10-20 22:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0002_DEV-2030_rp_deletion_cascades_to_template_and_page"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donationpage",
            name="post_thank_you_redirect",
            field=models.URLField(
                blank=True,
                help_text='Contributors can click a link to go "back to the news" after viewing the default thank you page',
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="post_thank_you_redirect",
            field=models.URLField(
                blank=True,
                help_text='Contributors can click a link to go "back to the news" after viewing the default thank you page',
            ),
        ),
    ]
