# Generated by Django 3.2.16 on 2022-10-28 16:05

from django.db import migrations, models


def populate_null_sidebar_elements_with_default_empty_list(apps, schema_editor):
    DonationPage = apps.get_model("pages", "DonationPage")
    Template = apps.get_model("pages", "Template")
    DonationPage.objects.filter(sidebar_elements__isnull=True).update(sidebar_elements=list())
    Template.objects.filter(sidebar_elements__isnull=True).update(sidebar_elements=list())


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_DEV-2030_rp_deletion_cascades_to_template_and_page"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donationpage",
            name="sidebar_elements",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="template",
            name="sidebar_elements",
            field=models.JSONField(default=list),
        ),
        migrations.RunPython(
            code=populate_null_sidebar_elements_with_default_empty_list,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
