# Generated by Django 3.2.16 on 2022-10-28 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_DEV-2030_rp_deletion_cascades_to_template_and_page"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donationpage",
            name="sidebar_elements",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="template",
            name="sidebar_elements",
            field=models.JSONField(default=list),
        ),
    ]
