# Generated by Django 3.2 on 2021-04-26 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
        ("pages", "0003_auto_20210426_1357"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donationpage",
            name="donor_benefits",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="donationpages",
                to="pages.donorbenefit",
            ),
        ),
        migrations.AlterField(
            model_name="donationpage",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="donationpages",
                to="organizations.organization",
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="donor_benefits",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="templates",
                to="pages.donorbenefit",
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="templates",
                to="organizations.organization",
            ),
        ),
    ]
