# Generated by Django 3.2.16 on 2022-10-28 16:05

from django.db import migrations, models


def populate_null_sidebar_elements_with_default_empty_list(apps, schema_editor):
    DonationPage = apps.get_model("pages", "DonationPage")
    Template = apps.get_model("pages", "Template")
    DonationPage.objects.filter(sidebar_elements__isnull=True).update(sidebar_elements=list())
    Template.objects.filter(sidebar_elements__isnull=True).update(sidebar_elements=list())


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0003_DEV-1446_rename_donation_in_help_text"),
    ]

    operations = [
        migrations.RunPython(
            code=populate_null_sidebar_elements_with_default_empty_list,
            reverse_code=migrations.RunPython.noop,
        )
    ]
