# Generated by Django 3.2 on 2021-04-26 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
        ("pages", "0004_auto_20210426_1429"),
    ]

    operations = [
        migrations.AlterField(
            model_name="benefit",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="benefits",
                to="organizations.organization",
            ),
        ),
        migrations.AlterField(
            model_name="benefittier",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="benefittiers",
                to="organizations.organization",
            ),
        ),
        migrations.AlterField(
            model_name="donationpage",
            name="revenue_program",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="donationpages",
                to="organizations.revenueprogram",
            ),
        ),
        migrations.AlterField(
            model_name="donorbenefit",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="donorbenefits",
                to="organizations.organization",
            ),
        ),
        migrations.AlterField(
            model_name="style",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="styles",
                to="organizations.organization",
            ),
        ),
    ]
