# Generated by Django 3.2.16 on 2022-11-01 20:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0004_DEV-1867_migrate_null_sidebar_elements_to_empty_list"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donationpage",
            name="sidebar_elements",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="template",
            name="sidebar_elements",
            field=models.JSONField(default=list),
        ),
    ]
