# Generated by Django 3.2 on 2021-04-27 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0003_donationpage_is_default_page"),
        ("pages", "0005_auto_20210426_1447"),
    ]

    operations = []
