# Generated by Django 3.2.16 on 2023-02-05 21:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0005_DEV-1867_sidebar_elements_default_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donationpage",
            name="sidebar_elements",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="template",
            name="sidebar_elements",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
