# Generated by Django 3.2.16 on 2023-01-26 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0005_DEV-1867_sidebar_elements_default_value"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Template",
        ),
    ]
