# Generated by Django 3.2 on 2021-05-07 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0006_auto_20210504_1827"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donationpage",
            name="slug",
            field=models.SlugField(
                blank=True, help_text="If not entered, it will be built from the Page name", unique=True
            ),
        ),
    ]
