# Generated by Django 3.2.16 on 2023-01-26 19:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0006_DEV-2948_allow_empty_sidebar_elements"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Template",
        ),
    ]
