# Generated by Django 3.2 on 2021-05-10 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0010_alter_organization_name"),
        ("pages", "0007_alter_donationpage_slug"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="donationpage",
            unique_together={("slug", "organization")},
        ),
    ]
