# Generated by Django 3.2.2 on 2021-05-20 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0012_merge_20210517_1310"),
        ("pages", "0008_alter_donationpage_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="donationpage",
            unique_together={("slug", "revenue_program")},
        ),
    ]
