# Generated by Django 3.2.20 on 2023-08-30 15:42

import apps.config.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0009_DEV_3689_donationpage_header_logo_alt_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donationpage",
            name="slug",
            field=models.SlugField(
                blank=True, null=True, validators=[apps.config.validators.validate_slug_against_denylist]
            ),
        ),
    ]
