# Generated by Django 3.2.20 on 2023-08-31 01:56

import apps.config.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0009_DEV_3689_donationpage_header_logo_alt_text"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="donationpage",
            name="unique_slug",
        ),
        migrations.AlterField(
            model_name="donationpage",
            name="slug",
            field=models.SlugField(null=True, validators=[apps.config.validators.validate_slug_against_denylist]),
        ),
        migrations.AddConstraint(
            model_name="donationpage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("slug__isnull", False)), fields=("revenue_program", "slug"), name="unique_slug"
            ),
        ),
    ]
