# Generated by Django 3.2.2 on 2021-05-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0009_alter_donationpage_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="donationpage",
            name="post_thank_you_redirect",
            field=models.URLField(
                blank=True, help_text='If left blank, Organization default post-"thank you" redirect will be used'
            ),
        ),
        migrations.AddField(
            model_name="donationpage",
            name="thank_you_redirect",
            field=models.URLField(
                blank=True, help_text='If left blank, Organization default "thank you" redirect will be used'
            ),
        ),
        migrations.AddField(
            model_name="template",
            name="post_thank_you_redirect",
            field=models.URLField(
                blank=True, help_text='If left blank, Organization default post-"thank you" redirect will be used'
            ),
        ),
        migrations.AddField(
            model_name="template",
            name="thank_you_redirect",
            field=models.URLField(
                blank=True, help_text='If left blank, Organization default "thank you" redirect will be used'
            ),
        ),
    ]
