# Generated by Django 3.2.2 on 2021-05-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0010_auto_20210524_1257"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donationpage",
            name="published_date",
            field=models.DateTimeField(null=True),
        ),
    ]
