# Generated by Django 3.2.2 on 2021-06-10 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0011_alter_donationpage_published_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="donationpage",
            name="title",
        ),
        migrations.RemoveField(
            model_name="template",
            name="title",
        ),
        migrations.AddField(
            model_name="donationpage",
            name="graphic",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="donationpage",
            name="heading",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="template",
            name="graphic",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="template",
            name="heading",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
