# Generated by Django 3.2.2 on 2021-06-10 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0011_alter_donationpage_published_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="donationpage",
            old_name="title",
            new_name="heading",
        ),
        migrations.RenameField(
            model_name="template",
            old_name="title",
            new_name="heading",
        ),
        migrations.AddField(
            model_name="donationpage",
            name="graphic",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="template",
            name="graphic",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
