# Generated by Django 3.2.2 on 2021-06-11 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0012_auto_20210610_1312"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donationpage",
            name="heading",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="template",
            name="heading",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
