# Generated by Django 3.2.2 on 2021-06-17 12:12

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0013_auto_20210611_1355"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donationpage",
            name="graphic",
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="donationpage",
            name="header_bg_image",
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="donationpage",
            name="header_logo",
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="template",
            name="graphic",
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="template",
            name="header_bg_image",
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="template",
            name="header_logo",
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
