# Generated by Django 3.2.2 on 2021-06-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0013_auto_20210611_1355"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donationpage",
            name="published_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
