# Generated by Django 3.2.2 on 2021-06-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0014_auto_20210617_1212"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donationpage",
            name="post_thank_you_redirect",
            field=models.URLField(
                blank=True,
                help_text='Donors can click a link to go "back to the news" after viewing the default thank you page',
            ),
        ),
        migrations.AlterField(
            model_name="donationpage",
            name="thank_you_redirect",
            field=models.URLField(
                blank=True, help_text="If not using default Thank You page, add link to orgs Thank You page here"
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="post_thank_you_redirect",
            field=models.URLField(
                blank=True,
                help_text='Donors can click a link to go "back to the news" after viewing the default thank you page',
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="thank_you_redirect",
            field=models.URLField(
                blank=True, help_text="If not using default Thank You page, add link to orgs Thank You page here"
            ),
        ),
    ]
