# Generated by Django 3.2.2 on 2021-06-17 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0015_auto_20210617_1533"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="donationpage",
            name="show_benefits",
        ),
        migrations.RemoveField(
            model_name="template",
            name="show_benefits",
        ),
    ]
