# Generated by Django 3.2.2 on 2021-06-21 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0014_alter_donationpage_published_date"),
        ("pages", "0016_auto_20210617_1602"),
    ]

    operations = []
