# Generated by Django 3.2.2 on 2021-06-25 15:30

import apps.pages.models
from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0017_merge_20210621_1528"),
    ]

    operations = [
        migrations.AddField(
            model_name="donationpage",
            name="page_screenshot",
            field=sorl.thumbnail.fields.ImageField(
                blank=True, null=True, upload_to=apps.pages.models._get_screenshot_upload_path
            ),
        ),
    ]
