# Generated by Django 3.2.2 on 2021-06-24 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0017_merge_20210621_1528"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donationpage",
            name="elements",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="template",
            name="elements",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
