# Generated by Django 3.2.2 on 2021-06-29 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0003_auto_20210629_1803"),
        ("pages", "0017_merge_20210621_1528"),
    ]

    operations = [
        migrations.AddField(
            model_name="donationpage",
            name="email_templates",
            field=models.ManyToManyField(to="emails.PageEmailTemplate"),
        ),
    ]
