# Generated by Django 3.2.2 on 2021-06-25 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0017_merge_20210621_1528"),
    ]

    operations = [
        migrations.AddField(
            model_name="donationpage",
            name="page_screenshot",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
