# Generated by Django 3.2.2 on 2021-07-06 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0018_auto_20210624_2008"),
        ("pages", "0019_alter_donationpage_email_templates"),
    ]

    operations = []
