# Generated by Django 3.2.5 on 2021-07-07 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0018_donationpage_page_screenshot"),
        ("pages", "0020_merge_20210706_1301"),
    ]

    operations = []
