# Generated by Django 3.2.5 on 2021-07-20 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0021_merge_20210707_1553"),
    ]

    operations = [
        migrations.AddField(
            model_name="donationpage",
            name="deleted",
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
