# Generated by Django 3.2.5 on 2021-08-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0022_donationpage_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="donationpage",
            name="sidebar_elements",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="sidebar_elements",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
