# Generated by Django 3.2.5 on 2021-08-05 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0022_donationpage_deleted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="donationpage",
            name="donor_benefits",
        ),
        migrations.RemoveField(
            model_name="template",
            name="donor_benefits",
        ),
    ]
