# Generated by Django 3.2.5 on 2021-08-05 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0023_auto_20210805_1707"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="benefittier",
            name="benefits",
        ),
        migrations.RemoveField(
            model_name="benefittier",
            name="organization",
        ),
        migrations.AlterUniqueTogether(
            name="donorbenefit",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="donorbenefit",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="donorbenefit",
            name="tiers",
        ),
        migrations.DeleteModel(
            name="Benefit",
        ),
        migrations.DeleteModel(
            name="BenefitTier",
        ),
        migrations.DeleteModel(
            name="DonorBenefit",
        ),
    ]
