# Generated by Django 3.2.5 on 2021-08-13 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0023_auto_20210810_1711"),
        ("pages", "0024_auto_20210805_1711"),
    ]

    operations = []
