# Generated by Django 3.2.5 on 2021-08-19 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0025_merge_0023_auto_20210810_1711_0024_auto_20210805_1711"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donationpage",
            name="slug",
            field=models.SlugField(
                blank=True,
                error_messages={"unique": "This slug has already been used"},
                help_text="If not entered, it will be built from the Page name",
                unique=True,
            ),
        ),
    ]
