# Generated by Django 3.2.5 on 2021-08-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0025_merge_0023_auto_20210810_1711_0024_auto_20210805_1711"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="style",
            options={"ordering": ["-created", "name"]},
        ),
        migrations.AddField(
            model_name="style",
            name="deleted",
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="style",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
