# Generated by Django 3.2.5 on 2021-09-01 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0026_alter_donationpage_slug"),
        ("pages", "0026_auto_20210820_1550"),
    ]

    operations = []
