# Generated by Django 3.2.5 on 2021-09-07 13:58

import apps.pages.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0027_merge_20210901_1553"),
    ]

    operations = [
        migrations.AlterField(
            model_name="style",
            name="styles",
            field=models.JSONField(validators=[apps.pages.validators.style_validator]),
        ),
    ]
