# Generated by Django 3.2.5 on 2021-09-10 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0028_alter_style_styles"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="donationpage",
            unique_together=set(),
        ),
    ]
