# Generated by Django 3.2.5 on 2021-11-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0041_revenueprogram_allow_offer_nyt_comp"),
        ("pages", "0029_alter_donationpage_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donationpage",
            name="slug",
            field=models.SlugField(
                blank=True,
                error_messages={"unique": "This slug has already been used"},
                help_text="If not entered, it will be built from the Page name",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="donationpage",
            unique_together={("slug", "revenue_program")},
        ),
    ]
