# Generated by Django 3.2.5 on 2021-11-22 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0030_auto_20211115_1542"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donationpage",
            name="slug",
            field=models.SlugField(
                blank=True,
                error_messages={"unique": "This slug is already in use on this Revenue Program"},
                help_text="If not entered, it will be built from the Page name",
            ),
        ),
    ]
