# Generated by Django 3.2.5 on 2021-11-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0031_alter_donationpage_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Font",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="This is how the font will be displayed in the Org admin", max_length=255
                    ),
                ),
                (
                    "source",
                    models.CharField(choices=[("typekit", "Typekit"), ("google", "Google fonts")], max_length=7),
                ),
                (
                    "font_name",
                    models.CharField(help_text="This is the name by which CSS will use the font", max_length=255),
                ),
                (
                    "accessor",
                    models.CharField(
                        help_text="For typekit fonts, use the kitId. For google fonts, use the value of the 'family' query param",
                        max_length=255,
                    ),
                ),
            ],
        ),
    ]
