# Generated by Django 3.2.5 on 2021-12-01 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0032_font"),
    ]

    operations = [
        migrations.AlterField(
            model_name="font",
            name="font_name",
            field=models.CharField(
                help_text="This is the name by which CSS will use the font", max_length=255, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="font",
            name="name",
            field=models.CharField(
                help_text="This is how the font will be displayed in the Org admin", max_length=255, unique=True
            ),
        ),
    ]
