# Generated by Django 3.2.5 on 2022-01-12 13:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0042_organization_stripe_oauth_refresh_token"),
        ("pages", "0033_auto_20211201_1549"),
    ]

    operations = [
        migrations.CreateModel(
            name="TranslatedPage",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        db_index=True, default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        db_index=True, default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("deleted", models.DateTimeField(editable=False, null=True)),
                ("name", models.CharField(max_length=255)),
                ("heading", models.CharField(blank=True, max_length=255)),
                ("graphic", sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to="")),
                ("header_bg_image", sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to="")),
                ("header_logo", sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to="")),
                ("header_link", models.URLField(blank=True, null=True)),
                ("elements", models.JSONField(blank=True, default=list, null=True)),
                ("sidebar_elements", models.JSONField(blank=True, default=list, null=True)),
                (
                    "thank_you_redirect",
                    models.URLField(
                        blank=True,
                        help_text="If not using default Thank You page, add link to orgs Thank You page here",
                    ),
                ),
                (
                    "post_thank_you_redirect",
                    models.URLField(
                        blank=True,
                        help_text='Donors can click a link to go "back to the news" after viewing the default thank you page',
                    ),
                ),
                ("language", models.CharField(max_length=20)),
                (
                    "organization",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="pages.donationpage",
                    ),
                ),
                (
                    "styles",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="pages.style"
                    ),
                ),
            ],
            options={
                "unique_together": {("page", "language")},
            },
        ),
    ]
