# Generated by Django 3.2.5 on 2022-01-18 15:58

from django.db import migrations
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0033_auto_20211201_1549"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="font",
            options={"ordering": [django.db.models.functions.text.Lower("name")]},
        ),
    ]
