# Generated by Django 3.2.5 on 2022-01-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0033_auto_20211201_1549"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donationpage",
            name="header_link",
            field=models.URLField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="template",
            name="header_link",
            field=models.URLField(blank=True, default=""),
            preserve_default=False,
        ),
    ]
