# Generated by Django 3.2.5 on 2022-01-18 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0034_alter_font_options"),
        ("pages", "0034_auto_20220110_1845"),
    ]

    operations = []
