# Generated by Django 3.2.5 on 2022-01-13 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0034_auto_20220110_1845"),
        ("pages", "0034_translatedpage"),
    ]

    operations = []
