# Generated by Django 3.2.5 on 2022-01-21 16:32

import apps.pages.defaults
from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0035_merge_0034_alter_font_options_0034_auto_20220110_1845"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donationpage",
            name="elements",
            field=models.JSONField(blank=True, default=apps.pages.defaults.get_default_page_elements, null=True),
        ),
        migrations.AlterField(
            model_name="donationpage",
            name="header_logo",
            field=sorl.thumbnail.fields.ImageField(
                blank=True, default=apps.pages.defaults.get_default_header_logo, null=True, upload_to=""
            ),
        ),
    ]
