# Generated by Django 3.2.5 on 2022-01-13 13:59

import apps.pages.models
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0042_organization_stripe_oauth_refresh_token"),
        ("emails", "0004_alter_pageemailtemplate_schema"),
        ("pages", "0035_merge_0034_auto_20220110_1845_0034_translatedpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="translatedpage",
            name="email_templates",
            field=models.ManyToManyField(blank=True, to="emails.PageEmailTemplate"),
        ),
        migrations.AddField(
            model_name="translatedpage",
            name="page_screenshot",
            field=sorl.thumbnail.fields.ImageField(
                blank=True, null=True, upload_to=apps.pages.models._get_screenshot_upload_path
            ),
        ),
        migrations.AddField(
            model_name="translatedpage",
            name="published_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="translatedpage",
            name="revenue_program",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="organizations.revenueprogram"
            ),
        ),
        migrations.AddField(
            model_name="translatedpage",
            name="slug",
            field=models.SlugField(
                blank=True,
                error_messages={"unique": "This slug is already in use on this Revenue Program"},
                help_text="If not entered, it will be built from the Page name",
            ),
        ),
        migrations.AlterField(
            model_name="translatedpage",
            name="header_link",
            field=models.URLField(blank=True, default=""),
            preserve_default=False,
        ),
    ]
