# Generated by Django 3.2.5 on 2022-01-24 14:46

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0036_auto_20220121_1838"),
    ]

    operations = [
        migrations.CreateModel(
            name="DefaultPageLogo",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("logo", sorl.thumbnail.fields.ImageField(null=True, upload_to="")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
