# Generated by Django 3.2.5 on 2022-01-13 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0036_auto_20220113_1359"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="translatedpage",
            name="deleted",
        ),
    ]
