# Generated by Django 3.2.5 on 2022-01-28 15:49

import apps.config.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0037_defaultpagelogo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donationpage",
            name="slug",
            field=models.SlugField(
                blank=True,
                error_messages={"unique": "This slug is already in use on this Revenue Program"},
                help_text="If not entered, it will be built from the Page name",
                validators=[apps.config.validators.validate_slug_against_denylist],
            ),
        ),
    ]
