# Generated by Django 3.2.5 on 2022-02-09 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0046_merge_20220203_1437"),
        ("pages", "0039_auto_20220207_1645"),
    ]

    operations = [
        migrations.AddField(
            model_name="style",
            name="revenue_program",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="organizations.revenueprogram"
            ),
        ),
        migrations.AlterField(
            model_name="style",
            name="organization",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="organizations.organization"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="style",
            unique_together={("name", "revenue_program")},
        ),
    ]
