# Generated by Django 3.2.5 on 2022-02-23 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0040_track_model_history"),
        ("pages", "0041_auto_20220209_1255"),
    ]

    operations = []
