# Generated by Django 3.2.5 on 2022-02-11 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0046_merge_20220203_1437"),
        ("pages", "0041_auto_20220209_1256"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="style",
            name="organization",
        ),
        migrations.AlterField(
            model_name="style",
            name="revenue_program",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="organizations.revenueprogram"),
        ),
    ]
