# Generated by Django 3.2.5 on 2022-02-22 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0041_initial_historical_record"),
        ("pages", "0042_auto_20220211_1522"),
    ]

    operations = []
