# Generated by Django 3.2.5 on 2022-02-23 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0048_initial_historical_record"),
        ("pages", "0043_merge_20220222_2008"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalstyle",
            name="organization",
        ),
        migrations.AddField(
            model_name="historicalstyle",
            name="revenue_program",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="organizations.revenueprogram",
            ),
        ),
    ]
