# Generated by Django 3.2.5 on 2022-02-23 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0051_historicalorganization_slug"),
        ("pages", "0044_auto_20220223_1837"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalstyle",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="style",
            name="organization",
        ),
        migrations.AddField(
            model_name="historicalstyle",
            name="revenue_program",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="organizations.revenueprogram",
            ),
        ),
        migrations.AlterField(
            model_name="style",
            name="revenue_program",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="organizations.revenueprogram"),
        ),
    ]
