# Generated by Django 3.2.13 on 2022-06-17 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0047_remove_donationpage_email_templates"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalfont",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalstyle",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalstyle",
            name="revenue_program",
        ),
        migrations.RemoveField(
            model_name="historicaltemplate",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicaltemplate",
            name="revenue_program",
        ),
        migrations.RemoveField(
            model_name="historicaltemplate",
            name="styles",
        ),
        migrations.RemoveField(
            model_name="donationpage",
            name="deleted",
        ),
        migrations.RemoveField(
            model_name="donationpage",
            name="deleted_by_cascade",
        ),
        migrations.RemoveField(
            model_name="style",
            name="deleted",
        ),
        migrations.RemoveField(
            model_name="style",
            name="deleted_by_cascade",
        ),
        migrations.DeleteModel(
            name="HistoricalDonationPage",
        ),
        migrations.DeleteModel(
            name="HistoricalFont",
        ),
        migrations.DeleteModel(
            name="HistoricalStyle",
        ),
        migrations.DeleteModel(
            name="HistoricalTemplate",
        ),
    ]
