# Generated by Django 3.2.13 on 2022-06-15 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0048_auto_20220615_1537"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="donationpage",
            name="deleted",
        ),
        migrations.RemoveField(
            model_name="donationpage",
            name="deleted_by_cascade",
        ),
        migrations.RemoveField(
            model_name="style",
            name="deleted",
        ),
        migrations.RemoveField(
            model_name="style",
            name="deleted_by_cascade",
        ),
    ]
