# Generated by Django 3.2.20 on 2023-09-19 20:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0010_DEV_3320"),
    ]

    operations = [
        migrations.AddField(
            model_name="donationpage",
            name="locale",
            field=models.CharField(default="en", max_length=20),
        ),
    ]
