export const HUB_STRIPE_PUBLISHABLE_KEY = process.env.HUB_STRIPE_PUBLISHABLE_KEY;
export const REACT_APP_API_VERSION = process.env.REACT_APP_API_VERSION || 'v1';
export const REACT_APP_SALESFORCE_CAMPAIGN_ID_QUERYPARAM =
  process.env.REACT_APP_SALESFORCE_CAMPAIGN_ID_QUERYPARAM || 'campaign';
export const REACT_APP_FREQUENCY_QUERYPARAM = process.env.REACT_APP_FREQUENCY_QUERYPARAM || 'frequency';
export const REACT_APP_AMOUNT_QUERYPARAM = process.env.REACT_APP_AMOUNT_QUERYPARAM || 'amount';
export const REACT_APP_CAPTURE_PAGE_SCREENSHOT = process.env.REACT_APP_CAPTURE_PAGE_SCREENSHOT === 'true';
