# Generated by Django 3.2.5 on 2021-08-16 18:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pages", "0025_merge_0023_auto_20210810_1711_0024_auto_20210805_1711"),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        db_index=True, default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        db_index=True, default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("spa_key", models.UUIDField(blank=True)),
                ("height", models.PositiveIntegerField()),
                ("width", models.PositiveIntegerField()),
                (
                    "image",
                    sorl.thumbnail.fields.ImageField(height_field="height", upload_to="images", width_field="width"),
                ),
                ("thumbnail", models.ImageField(blank=True, null=True, upload_to="images/thumbs")),
                ("image_attrs", models.JSONField(blank=True, null=True)),
                ("page_id", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="pages.donationpage")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
