# Generated by Django 3.2.13 on 2022-06-24 02:35

import django.utils.timezone
from django.db import migrations, models

import model_utils.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MediaImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        db_index=True, default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        db_index=True, default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("spa_key", models.UUIDField(blank=True)),
                ("image", models.ImageField(null=True, upload_to="images")),
                ("thumbnail", models.ImageField(blank=True, null=True, upload_to="thumbs")),
                ("image_attrs", models.JSONField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
