# Generated by Django 3.2.5 on 2021-08-17 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("element_media", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mediaimage",
            name="height",
        ),
        migrations.RemoveField(
            model_name="mediaimage",
            name="width",
        ),
        migrations.AlterField(
            model_name="mediaimage",
            name="image",
            field=models.ImageField(null=True, upload_to="images"),
        ),
    ]
