# Generated by Django 4.2.20 on 2025-05-29 20:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contributions", "0019_DEV-5953_alter_contribution_contributor"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionalEmailRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        db_index=True, default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        db_index=True, default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("name", models.CharField(choices=[("failed-payment-notification", "failed payment")], max_length=50)),
                ("sent_on", models.CharField(default="pending", max_length=50)),
                (
                    "contribution",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contributions.contribution"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
