# Generated by Django 4.2.21 on 2025-05-30 16:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0030_DEV-5977_organization_disable_reminder_emails"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailCustomization",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        db_index=True, default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        db_index=True, default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("content_html", models.TextField(help_text="HTML source code of the custom content", max_length=5000)),
                (
                    "email_type",
                    models.CharField(
                        choices=[("contribution_receipt", "Contribution Receipt")],
                        help_text="Type of email this relates to",
                        max_length=30,
                    ),
                ),
                (
                    "email_block",
                    models.CharField(
                        choices=[("message", "Main Message Body")],
                        help_text="Which block of content in an email this relates to",
                        max_length=30,
                    ),
                ),
                (
                    "revenue_program",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to="organizations.revenueprogram"
                    ),
                ),
            ],
            options={
                "unique_together": {("revenue_program", "email_type", "email_block")},
            },
        ),
    ]
