# Generated by Django 3.2.2 on 2021-06-07 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pages", "0010_auto_20210524_1257"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionalEmailTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("identifier", models.CharField(blank=True, max_length=256)),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("OTD", "One Time Donation"),
                            ("RCD", "Recurring Donation"),
                            ("FLD", "Failed Payment"),
                            ("CAN", "Cancelled Donation"),
                        ],
                        default="OTD",
                        max_length=3,
                    ),
                ),
                ("schema", models.JSONField(blank=True)),
                (
                    "donation_page",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="pages.donationpage"),
                ),
            ],
            options={
                "unique_together": {("donation_page", "identifier")},
            },
        ),
    ]
