# Generated by Django 3.2.2 on 2021-06-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MailGunEmailTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("identifier", models.TextField(blank=True)),
                ("merge_data", models.JSONField(blank=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
