# Generated by Django 3.2.2 on 2021-06-09 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0010_auto_20210524_1257"),
        ("emails", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageEmailTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "identifier",
                    models.CharField(
                        blank=True, help_text="This should match the template name on the ESP", max_length=256
                    ),
                ),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("OTD", "One Time Donation"),
                            ("RCD", "Recurring Donation"),
                            ("FLD", "Failed Payment"),
                            ("CAN", "Cancelled Donation"),
                        ],
                        default="OTD",
                        max_length=3,
                    ),
                ),
                ("schema", models.JSONField(blank=True, default=dict, null=True)),
                (
                    "donation_page",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="pages.donationpage"
                    ),
                ),
            ],
            options={
                "unique_together": {("donation_page", "identifier", "template_type")},
            },
        ),
        migrations.DeleteModel(
            name="TransactionalEmailTemplate",
        ),
    ]
