# Generated by Django 4.2.21 on 2025-06-09 19:06

import datetime

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("contributions", "0019_DEV-5953_alter_contribution_contributor"),
        ("emails", "0001_DEV-6141_add_email_customization_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionalEmailRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        db_index=True, default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        db_index=True, default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("name", models.CharField(choices=[("receipt_email", "receipt email")], max_length=50)),
                ("sent_on", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "contribution",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contributions.contribution"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
