# Generated by Django 4.2.23 on 2025-07-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0002_DEV-6233_transactionalemailrecord"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="transactionalemailrecord",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="transactionalemailrecord",
            name="unique_identifier",
            field=models.CharField(
                blank=True,
                help_text="A unique identifier for the email, such as a webhook event ID or similar to ensure transactional emails are not sent multiple times for the same event.",
                max_length=300,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="emailcustomization",
            name="email_type",
            field=models.CharField(
                choices=[
                    ("contribution_receipt", "Contribution Receipt"),
                    ("annual_payment_reminder", "Annual Payment Reminder"),
                ],
                help_text="Type of email this relates to",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="transactionalemailrecord",
            name="name",
            field=models.CharField(
                choices=[
                    ("contribution_receipt", "Contribution Receipt"),
                    ("annual_payment_reminder", "Annual Payment Reminder"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddConstraint(
            model_name="transactionalemailrecord",
            constraint=models.UniqueConstraint(
                condition=models.Q(("unique_identifier__isnull", False)),
                fields=("contribution", "name", "unique_identifier"),
                name="contribution_name_unique_identifier_when_not_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="transactionalemailrecord",
            constraint=models.UniqueConstraint(
                condition=models.Q(("unique_identifier__isnull", True)),
                fields=("contribution", "name"),
                name="contribution_name_unique_identifier_when_null",
            ),
        ),
    ]
