# Generated by Django 3.2.2 on 2021-06-29 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0002_auto_20210609_1543"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="pageemailtemplate",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="pageemailtemplate",
            name="donation_page",
        ),
    ]
