# Generated by Django 3.2.2 on 2021-06-30 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0003_auto_20210629_1803"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pageemailtemplate",
            name="schema",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
