# Generated by Django 3.2.13 on 2022-05-06 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0047_remove_donationpage_email_templates"),
        ("emails", "0006_initial_historical_record"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalpageemailtemplate",
            name="history_user",
        ),
        migrations.DeleteModel(
            name="PageEmailTemplate",
        ),
        migrations.DeleteModel(
            name="HistoricalPageEmailTemplate",
        ),
    ]
