# Generated by Django 3.2.13 on 2022-06-24 02:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organizations", "0001_initial"),
        ("common", "0001_initial"),
        ("users", "0002_auto_20220624_0235"),
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="revenueprogram",
            name="default_donation_page",
            field=models.ForeignKey(
                blank=True,
                help_text="Choose an optional default donation page once you've saved your initial revenue program",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pages.donationpage",
            ),
        ),
        migrations.AddField(
            model_name="revenueprogram",
            name="organization",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"),
        ),
        migrations.AddField(
            model_name="revenueprogram",
            name="payment_provider",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="organizations.paymentprovider"
            ),
        ),
        migrations.AddField(
            model_name="revenueprogram",
            name="social_meta",
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to="common.socialmeta"),
        ),
        migrations.AddField(
            model_name="plan",
            name="features",
            field=models.ManyToManyField(blank=True, related_name="plans", to="organizations.Feature"),
        ),
        migrations.AddField(
            model_name="organization",
            name="address",
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="common.address"),
        ),
        migrations.AddField(
            model_name="organization",
            name="plan",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="organizations.plan"),
        ),
        migrations.AddField(
            model_name="organization",
            name="users",
            field=models.ManyToManyField(through="users.OrganizationUser", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name="feature",
            unique_together={("feature_type", "feature_value")},
        ),
        migrations.AddField(
            model_name="benefitlevelbenefit",
            name="benefit",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="organizations.benefit"),
        ),
        migrations.AddField(
            model_name="benefitlevelbenefit",
            name="benefit_level",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="organizations.benefitlevel"),
        ),
        migrations.AddField(
            model_name="benefitlevel",
            name="benefits",
            field=models.ManyToManyField(through="organizations.BenefitLevelBenefit", to="organizations.Benefit"),
        ),
        migrations.AddField(
            model_name="benefitlevel",
            name="revenue_program",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="organizations.revenueprogram"),
        ),
        migrations.AddField(
            model_name="benefit",
            name="revenue_program",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="organizations.revenueprogram"),
        ),
        migrations.AlterUniqueTogether(
            name="benefitlevel",
            unique_together={("name", "revenue_program")},
        ),
        migrations.AlterUniqueTogether(
            name="benefit",
            unique_together={("name", "revenue_program")},
        ),
    ]
