# Generated by Django 3.2 on 2021-04-26 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="organization",
            name="non_profit",
            field=models.BooleanField(default=True, verbose_name="Non-profit?"),
        ),
        migrations.AddField(
            model_name="organization",
            name="org_addr1",
            field=models.CharField(blank=True, max_length=255, verbose_name="Address 1"),
        ),
        migrations.AddField(
            model_name="organization",
            name="org_addr2",
            field=models.CharField(blank=True, max_length=255, verbose_name="Address 2"),
        ),
        migrations.AddField(
            model_name="organization",
            name="org_city",
            field=models.CharField(blank=True, max_length=64, verbose_name="City"),
        ),
        migrations.AddField(
            model_name="organization",
            name="org_state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AL", "Alabama"),
                    ("AK", "Alaska"),
                    ("AZ", "Arizona"),
                    ("AR", "Arkansas"),
                    ("CA", "California"),
                    ("CO", "Colorado"),
                    ("CT", "Connecticut"),
                    ("DC", "Washington D.C."),
                    ("DE", "Delaware"),
                    ("FL", "Florida"),
                    ("GA", "Georgia"),
                    ("HI", "Hawaii"),
                    ("ID", "Idaho"),
                    ("IL", "Illinois"),
                    ("IN", "Indiana"),
                    ("IA", "Iowa"),
                    ("KS", "Kansas"),
                    ("LA", "Louisiana"),
                    ("ME", "Maine"),
                    ("MD", "Maryland"),
                    ("MA", "Massachusetts"),
                    ("MI", "Michigan"),
                    ("MN", "Minnesota"),
                    ("MS", "Mississippi"),
                    ("MO", "Missouri"),
                    ("MT", "Montana"),
                    ("NE", "Nebraska"),
                    ("NV", "Nevada"),
                    ("NH", "New Hampshire"),
                    ("NJ", "New Jersey"),
                    ("NM", "New Mexico"),
                    ("NY", "New York"),
                    ("NC", "North Carolina"),
                    ("ND", "North Dakota"),
                    ("OH", "Ohio"),
                    ("OK", "Oklahoma"),
                    ("OR", "Oregon"),
                    ("PA", "Pennsylvania"),
                    ("RI", "Rhode Island"),
                    ("SC", "South Carolina"),
                    ("SD", "South Dakota"),
                    ("TN", "Tennessee"),
                    ("TX", "Texas"),
                    ("UT", "Utah"),
                    ("VT", "Vermont"),
                    ("VA", "Virginia"),
                    ("WA", "Washington"),
                    ("WI", "Wisconsin"),
                    ("WY", "Wyoming"),
                ],
                max_length=2,
                verbose_name="State",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="org_zip",
            field=models.CharField(blank=True, max_length=9, verbose_name="Zip"),
        ),
        migrations.AddField(
            model_name="organization",
            name="salesforce_id",
            field=models.CharField(blank=True, max_length=255, verbose_name="Salesforce ID"),
        ),
        migrations.AddField(
            model_name="organization",
            name="stripe_account",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="revenueprogram",
            name="slug",
            field=models.SlugField(max_length=100),
        ),
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "plans",
                    models.ManyToManyField(blank=True, related_name="plans", to="organizations.Plan"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="organization",
            name="plan",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="organizations.plan"),
        ),
    ]
