# Generated by Django 3.2 on 2021-05-04 18:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_auto_20210423_1718"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organizations", "0002_auto_20210428_1641"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="users",
            field=models.ManyToManyField(through="users.OrganizationUser", to=settings.AUTH_USER_MODEL),
        ),
    ]
