# Generated by Django 3.2 on 2021-05-04 15:22

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import djstripe.fields


class Migration(migrations.Migration):

    dependencies = [
        ("djstripe", "0007_2_4"),
        ("organizations", "0002_organization_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="stripe_account",
            field=djstripe.fields.StripeForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="djstripe.account",
                to_field=settings.DJSTRIPE_FOREIGN_KEY_TO_FIELD,
            ),
        ),
    ]
