# Generated by Django 3.2 on 2021-05-06 15:58

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_auto_20210428_1641"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="created",
            field=model_utils.fields.AutoCreatedField(
                db_index=True,
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="created",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="default_payment_provider",
            field=models.CharField(choices=[("stripe", "Stripe")], default="stripe", max_length=100),
        ),
        migrations.AddField(
            model_name="organization",
            name="modified",
            field=model_utils.fields.AutoLastModifiedField(
                db_index=True,
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="modified",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="stripe_account_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="revenueprogram",
            name="created",
            field=model_utils.fields.AutoCreatedField(
                db_index=True,
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="created",
            ),
        ),
        migrations.AddField(
            model_name="revenueprogram",
            name="modified",
            field=model_utils.fields.AutoLastModifiedField(
                db_index=True,
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="modified",
            ),
        ),
    ]
