# Generated by Django 3.2 on 2021-05-07 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0003_auto_20210506_1558"),
        ("organizations", "0003_organization_users"),
    ]

    operations = []
