# Generated by Django 3.2.14 on 2022-07-08 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0003_DEV-1757_uses_email_templates"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="address",
        ),
        migrations.RemoveField(
            model_name="revenueprogram",
            name="address",
        ),
    ]
