# Generated by Django 3.2.14 on 2022-07-08 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0003_DEV-1757_uses_email_templates"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="country",
            field=models.CharField(
                blank=True, choices=[("US", "US"), ("CA", "CA")], default="US", max_length=2, verbose_name="Country"
            ),
        ),
    ]
