# Generated by Django 3.2.14 on 2022-07-08 04:16

from django.db import migrations


def populate_org_country_from_old_related_addresses(apps, schema_editor):
    """ """
    Organization = apps.get_model("organizations", "Organization")
    for org in Organization.objects.filter(address__isnull=False).all():
        org.country = org.address.country
        org.save()


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0004_DEV-2049_add_organization_country"),
    ]

    operations = [migrations.RunPython(populate_org_country_from_old_related_addresses, migrations.RunPython.noop)]
