# Generated by Django 3.2 on 2021-05-07 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0004_merge_0003_auto_20210506_1558_0003_organization_users"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="stripe_account",
        ),
    ]
