# Generated by Django 3.2.14 on 2022-07-08 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0005_DEV-2049_data_migration_org_country_from_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="address",
        ),
        migrations.RemoveField(
            model_name="revenueprogram",
            name="address",
        ),
    ]
