# Generated by Django 3.2 on 2021-05-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0005_remove_organization_stripe_account"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feature",
            name="plans",
        ),
        migrations.AddField(
            model_name="feature",
            name="feature_type",
            field=models.CharField(
                choices=[("PL", "Page Limit"), ("ES", "Enhanced Support")], default="PL", max_length=2
            ),
        ),
        migrations.AddField(
            model_name="feature",
            name="feature_value",
            field=models.CharField(blank=True, help_text="Use 1 for True 0 for False", max_length=32),
        ),
        migrations.AddField(
            model_name="plan",
            name="features",
            field=models.ManyToManyField(blank=True, related_name="plans", to="organizations.Feature"),
        ),
    ]
