# Generated by Django 3.2 on 2021-05-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0005_remove_organization_stripe_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="stripe_verified",
            field=models.BooleanField(default=False),
        ),
    ]
