# Generated by Django 3.2.14 on 2022-07-08 19:52

from django.db import migrations


def migrate_relationship_to_socialmeta_model(apps, schema_editor):
    """"""
    RevenueProgram = apps.get_model("organizations", "RevenueProgram")
    for rp in RevenueProgram.objects.filter(social_meta__isnull=False).all():
        rp.social_meta.revenue_program = rp
        rp.social_meta.save()


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0005_DEV-2030_alter_organization_plan"),
        ("common", "0003_DEV-2031_socialmeta_revenue_program"),
    ]

    operations = [
        migrations.RunPython(
            code=migrate_relationship_to_socialmeta_model,
            reverse_code=migrations.operations.special.RunPython.noop,
        )
    ]
