# Generated by Django 3.2.14 on 2022-07-21 18:24

from django.db import migrations


# NB: This migration originally was included in 0006_DEV-2031_refactor_socialmeta but
# it turns out it needs to be separate, because having data migration and model change in same
# caused problems. This only became apparent in working on DEV-2129 (
# https://news-revenue-hub.atlassian.net/jira/software/c/projects/DEV/boards/3?modal=detail&selectedIssue=DEV-2129)
# wherein I discovered that the original data migration for adding revenue program to social meta instances
# was not in fact saving the updated social meta instances.


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0006_DEV-2031_refactor_socialmeta"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="revenueprogram",
            name="social_meta",
        ),
    ]
