# Generated by Django 3.2 on 2021-05-07 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0006_auto_20210507_1924"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name="revenueprogram",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
