# Generated by Django 3.2.15 on 2022-09-20 14:24
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0007_DEV-2129_remove_revenueprogram_social_meta"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plan",
            name="features",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="plan",
        ),
        migrations.DeleteModel(
            name="Feature",
        ),
        migrations.DeleteModel(
            name="Plan",
        ),
        migrations.AddField(
            model_name="organization",
            name="plan",
            field=models.CharField(choices=[("FREE", "Free"), ("PLUS", "Plus")], default="FREE", max_length=10),
        ),
    ]
