# Generated by Django 3.2.15 on 2022-09-20 14:24
from django.db import migrations, models

# from https://news-revenue-hub.atlassian.net/wiki/spaces/TECH/pages/2214625287/Existing+Client+Donation+Page+URLs
# as of 9/19/22
rp_slugs_for_legacy_clients = [
    "anthropocene",
    "aspenjournalism",
    "berkeleyside",
    "bethesdabeat",
    "billypenn",
    "borderless",
    "cal-matters-rp-1",
    "capitalbnews",
    "capitaltimes",
    "carolinapublicpress",
    "citylimits",
    "cityside",
    "codastory",
    "colab-rp1",
    "cpi",
    "ct-mirror",
    "fortworthreport",
    "hechingerreport",
    "inside-climate-news-rp-1",
    "matternews",
    "mississippitoday",
    "montana-free-press",
    "nevada-independent-rp-1",
    "newsrevenuehub",
    "njspotlight",
    "noozhawk-rp1",
    "oaklandside",
    "occrp",
    "politifact",
    "religionnews",
    "sahanjournal",
    "san-jose-spotlight",
    "searchlightnm ",
    "the-city",
    "the74",
    "thelens",
    "washingtoncitypaper",
    "wisconsinwatch",
    "wlrn",
    "wyofile",
    "youthradio",
]


def migrate_legacy_clients_to_plus_plan(apps, schema_editor):
    """This migrates existing legacy client orgs to the PLUS plan, ahead of remove feature and plan
    models.
    """
    # RevenueProgram = apps.get_model("organizations", "RevenueProgram")
    Organization = apps.get_model("organizations", "Organization")
    Organization.objects.filter(revenueprogram__slug__in=rp_slugs_for_legacy_clients).update(plan_name="PLUS")


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0007_DEV-2129_remove_revenueprogram_social_meta"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="plan_name",
            field=models.CharField(choices=[("FREE", "Free"), ("PLUS", "Plus")], default="FREE", max_length=10),
        ),
        migrations.RunPython(
            code=migrate_legacy_clients_to_plus_plan,
            reverse_code=migrations.operations.special.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="plan",
            name="features",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="plan",
        ),
        migrations.DeleteModel(
            name="Feature",
        ),
        migrations.DeleteModel(
            name="Plan",
        ),
        migrations.RenameField(
            model_name="organization",
            old_name="plan_name",
            new_name="plan",
        ),
    ]
