# Generated by Django 3.2 on 2021-05-07 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0007_auto_20210507_2015"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="feature",
            unique_together={("feature_type", "feature_value")},
        ),
    ]
