# Generated by Django 3.2.16 on 2022-10-20 22:05

import django.db.models.deletion
from django.db import migrations, models

import apps.config.validators


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0003_DEV-1446_rename_donation_in_help_text"),
        ("organizations", "0008_DEV-2178_refactor_plan_modeling_and_migrate_legacy_clients"),
    ]

    operations = [
        migrations.AlterField(
            model_name="benefit",
            name="description",
            field=models.TextField(help_text="The text that appears on the contribution page"),
        ),
        migrations.AlterField(
            model_name="revenueprogram",
            name="allow_offer_nyt_comp",
            field=models.BooleanField(
                default=False,
                help_text="Should page authors for this Revenue Program see the option to offer their contributors a comp subscription to the New York Times?",
                verbose_name="Allow page editors to offer an NYT subscription",
            ),
        ),
        migrations.AlterField(
            model_name="revenueprogram",
            name="default_donation_page",
            field=models.ForeignKey(
                blank=True,
                help_text="Choose an optional default contribution page once you've saved your initial revenue program",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pages.donationpage",
            ),
        ),
        migrations.AlterField(
            model_name="revenueprogram",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="This will be used as the subdomain for contribution pages made under this revenue program. If left blank, it will be derived from the Revenue Program name.",
                max_length=63,
                unique=True,
                validators=[apps.config.validators.validate_slug_against_denylist],
            ),
        ),
        migrations.AlterField(
            model_name="revenueprogram",
            name="twitter_handle",
            field=models.CharField(
                blank=True,
                help_text="How can your contributors mention you on Twitter? Don't include '@' symbol",
                max_length=15,
            ),
        ),
    ]
