# Generated by Django 3.2.16 on 2022-10-28 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0008_DEV-2178_refactor_plan_modeling_and_migrate_legacy_clients"),
    ]

    operations = [
        migrations.RenameField(
            model_name="organization",
            old_name="plan",
            new_name="plan_name",
        ),
    ]
