# Generated by Django 3.2 on 2021-05-08 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0008_alter_feature_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feature",
            name="feature_type",
            field=models.CharField(choices=[("PL", "Page Limit"), ("BL", "Boolean")], default="PL", max_length=2),
        ),
        migrations.AlterField(
            model_name="feature",
            name="feature_value",
            field=models.CharField(
                blank=True, help_text="If feature type is Boolean, valid inputs are 't', 'f', '1', '0", max_length=32
            ),
        ),
    ]
