# Generated by Django 3.2 on 2021-05-13 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0007_alter_organization_stripe_verified"),
        ("organizations", "0010_alter_organization_name"),
    ]

    operations = []
