# Generated by Django 3.2.15 on 2022-11-01 21:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0010_DEV-1867_rename_plan_organization_plan_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="revenueprogram",
            name="tax_id",
            field=models.CharField(
                blank=True, max_length=9, null=True, validators=[django.core.validators.MinLengthValidator(9)]
            ),
        ),
    ]
