# Generated by Django 3.2.2 on 2021-05-18 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0011_alter_feature_feature_value"),
        ("organizations", "0011_merge_20210513_1816"),
    ]

    operations = []
