# Generated by Django 3.2.2 on 2021-05-20 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0009_alter_donationpage_unique_together"),
        ("organizations", "0013_revenueprogram_default_donation_page"),
    ]

    operations = [
        migrations.AlterField(
            model_name="revenueprogram",
            name="default_donation_page",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="pages.donationpage"
            ),
        ),
    ]
