# Generated by Django 3.2.16 on 2023-01-18 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0014_DEV_2721_merge_migration"),
    ]

    operations = [
        migrations.AddField(
            model_name="revenueprogram",
            name="fiscal_sponsor_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
