# Generated by Django 3.2.2 on 2021-05-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0014_alter_revenueprogram_default_donation_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="default_post_thank_you_redirect",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="default_thank_you_redirect",
            field=models.URLField(blank=True),
        ),
    ]
