# Generated by Django 3.2.16 on 2023-02-02 05:32

from django.db import migrations, models


def populate_fiscal_status(apps, _):
    rp_model = apps.get_model("organizations", "RevenueProgram")
    for rp in rp_model.objects.all():
        rp.fiscal_status = "nonprofit" if rp.non_profit else "for-profit"
        rp.save()


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0014_DEV_2721_merge_migration"),
    ]

    operations = [
        migrations.AddField(
            model_name="revenueprogram",
            name="fiscal_sponsor_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="revenueprogram",
            name="fiscal_status",
            field=models.TextField(
                choices=[
                    ("for-profit", "For Profit"),
                    ("nonprofit", "Nonprofit"),
                    ("fiscally sponsored", "Fiscally Sponsored"),
                ],
                default="nonprofit",
            ),
        ),
        migrations.RunPython(populate_fiscal_status),
        migrations.RemoveField(
            model_name="revenueprogram",
            name="non_profit",
        ),
    ]
