# Generated by Django 3.2.2 on 2021-05-28 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0015_auto_20210524_1257"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="stripe_product_id",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
