# Generated by Django 3.2.16 on 2023-03-02 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0015_DEV-3131_organization_add_fiscal_status_fiscal_sponsor_name_remove_nonprofit"),
    ]

    operations = [
        migrations.AddField(
            model_name="revenueprogram",
            name="mailchimp_access_token",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="revenueprogram",
            name="mailchimp_server_prefix",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
