# Generated by Django 3.2.18 on 2023-03-23 20:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0016_DEV-3297_add_mailchimp_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="plan_name",
            field=models.CharField(
                choices=[("FREE", "Free"), ("PLUS", "Plus"), ("CORE", "Core")], default="FREE", max_length=10
            ),
        ),
    ]
