# Generated by Django 3.2.2 on 2021-06-17 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0016_organization_stripe_product_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="default_post_thank_you_redirect",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="default_thank_you_redirect",
        ),
    ]
