# Generated by Django 3.2.18 on 2023-03-07 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0016_DEV-3297_add_mailchimp_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="revenueprogram",
            name="mailchimp_access_token",
        ),
    ]
