# Generated by Django 3.2.18 on 2023-03-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0017_DEV-3182_alter_organization_plan_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="revenueprogram",
            name="mailchimp_server_prefix",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
