# Generated by Django 3.2.5 on 2021-07-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0017_auto_20210617_1533"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="domain_apple_verified_date",
            field=models.DateTimeField(null=True),
        ),
    ]
