# Generated by Django 3.2.2 on 2021-07-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0017_auto_20210617_1533"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="privacy_policy_url",
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="organization",
            name="terms_of_service_url",
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
