# Generated by Django 3.2.18 on 2023-05-01 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0018_DEV-3297_alter_revenueprogram_mailchimp_server_prefix"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="revenueprogram",
            name="mailchimp_access_token",
        ),
    ]
