# Generated by Django 3.2.2 on 2021-07-05 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0018_auto_20210705_1847"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="privacy_policy_url",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="terms_of_service_url",
        ),
    ]
