# Generated by Django 3.2.18 on 2023-04-24 20:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0018_DEV-3297_alter_revenueprogram_mailchimp_server_prefix"),
    ]

    operations = [
        migrations.AddField(
            model_name="revenueprogram",
            name="mailchimp_list_id",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="revenueprogram",
            name="mailchimp_product_id",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="revenueprogram",
            name="mailchimp_store_id",
            field=models.TextField(blank=True, null=True),
        ),
    ]
