# Generated by Django 3.2.5 on 2021-07-16 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0018_organization_domain_apple_verified_date"),
        ("organizations", "0019_auto_20210705_1954"),
    ]

    operations = []
