# Generated by Django 3.2.5 on 2021-07-21 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0020_merge_20210716_1426"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="uses_email_templates",
            field=models.BooleanField(default=False),
        ),
    ]
