# Generated by Django 3.2.19 on 2023-07-17 14:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0020_DEV-3303_add_rp_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="stripe_subscription_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
