# Generated by Django 3.2.19 on 2023-07-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0020_DEV-3303_add_rp_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="stripe_subscription_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
