# Generated by Django 3.2.5 on 2021-07-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0021_organization_uses_email_templates"),
    ]

    operations = [
        migrations.AddField(
            model_name="revenueprogram",
            name="org_google_analytics_domain",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="revenueprogram",
            name="org_google_analytics_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
