# Generated by Django 3.2.5 on 2021-08-06 13:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0021_organization_uses_email_templates"),
    ]

    operations = [
        migrations.CreateModel(
            name="Benefit",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        db_index=True, default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        db_index=True, default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("name", models.CharField(help_text="A way to uniquely identify this Benefit", max_length=128)),
                (
                    "description",
                    models.CharField(help_text="The text that appears on the donation page", max_length=255),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BenefitLevel",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        db_index=True, default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        db_index=True, default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("lower_limit", models.PositiveIntegerField()),
                ("upper_limit", models.PositiveIntegerField()),
                ("currency", models.CharField(default="usd", max_length=3)),
            ],
        ),
        migrations.AlterField(
            model_name="organization",
            name="domain_apple_verified_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="RevenueProgramBenefitLevel",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "level",
                    models.PositiveSmallIntegerField(help_text="Is this a first-level benefit, second-level, etc?"),
                ),
                (
                    "benefit_level",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="organizations.benefitlevel"),
                ),
                (
                    "revenue_program",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="organizations.revenueprogram"),
                ),
            ],
            options={
                "ordering": ("level",),
            },
        ),
        migrations.CreateModel(
            name="BenefitLevelBenefit",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        help_text="The order in which this Benefit appears in this BenefitLevel"
                    ),
                ),
                ("benefit", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="organizations.benefit")),
                (
                    "benefit_level",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="organizations.benefitlevel"),
                ),
            ],
            options={
                "ordering": ("order",),
            },
        ),
        migrations.AddField(
            model_name="benefitlevel",
            name="organization",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"),
        ),
        migrations.AddField(
            model_name="benefit",
            name="organization",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"),
        ),
        migrations.AddField(
            model_name="revenueprogram",
            name="benefit_levels",
            field=models.ManyToManyField(
                null=True, through="organizations.RevenueProgramBenefitLevel", to="organizations.BenefitLevel"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="benefitlevel",
            unique_together={("name", "organization")},
        ),
        migrations.AlterUniqueTogether(
            name="benefit",
            unique_together={("name", "organization")},
        ),
    ]
