# Generated by Django 3.2.5 on 2021-08-09 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0021_organization_uses_email_templates"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=255),
        ),
    ]
