# Generated by Django 3.2.5 on 2021-08-10 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0022_auto_20210727_1727"),
    ]

    operations = [
        migrations.RenameField(
            model_name="revenueprogram",
            old_name="org_google_analytics_domain",
            new_name="google_analytics_v3_domain",
        ),
        migrations.RenameField(
            model_name="revenueprogram",
            old_name="org_google_analytics_id",
            new_name="google_analytics_v3_id",
        ),
    ]
