# Generated by Django 3.2.23 on 2023-12-21 14:41

from django.db import migrations


def create_default_social_meta(apps, schema_editor):
    RevenueProgram = apps.get_model("organizations", "RevenueProgram")
    SocialMeta = apps.get_model("common", "SocialMeta")
    for rp in RevenueProgram.objects.filter(socialmeta__isnull=True):
        SocialMeta.objects.create(revenue_program=rp)


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0022_DEV-3907_decrease_org_name_max_length"),
    ]

    operations = [
        migrations.RunPython(create_default_social_meta),
    ]
