# Generated by Django 3.2.5 on 2021-08-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0023_auto_20210806_1512"),
    ]

    operations = [
        migrations.AlterField(
            model_name="benefit",
            name="description",
            field=models.TextField(help_text="The text that appears on the donation page"),
        ),
    ]
