# Generated by Django 3.2.23 on 2024-03-06 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0023_DEV-4264_create_social_meta_for_existing_rps"),
    ]

    operations = [
        migrations.AddField(
            model_name="revenueprogram",
            name="contributor_portal_show_appeal",
            field=models.BooleanField(
                default=True,
                help_text="Should an appeal to contribute be shown in the this organization's? contributor portal?",
            ),
        ),
    ]
