# Generated by Django 3.2.25 on 2024-04-16 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0024_DEV-3870_add_contact_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="revenueprogram",
            name="mailchimp_all_contributors_segment_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
