# Generated by Django 3.2.5 on 2021-08-06 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0024_alter_benefit_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="benefit",
            options={"ordering": ["benefitlevelbenefit__order"]},
        ),
        migrations.AlterModelOptions(
            name="benefitlevel",
            options={"ordering": ["revenueprogrambenefitlevel__level"]},
        ),
    ]
