# Generated by Django 3.2.5 on 2021-08-10 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0024_revenueprogram_org_google_analytics_v4_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="revenueprogram",
            old_name="org_google_analytics_v3_domain",
            new_name="google_analytics_v3_domain",
        ),
        migrations.RenameField(
            model_name="revenueprogram",
            old_name="org_google_analytics_v3_id",
            new_name="google_analytics_v3_id",
        ),
    ]
