# Generated by Django 3.2.5 on 2021-08-10 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0022_organization_contact_email"),
        ("organizations", "0025_auto_20210806_1852"),
    ]

    operations = []
