# Generated by Django 3.2.25 on 2024-06-06 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0025_DEV-4244_revenueprogram_mailchimp_all_contributors_segment_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="revenueprogram",
            name="contributor_portal_show_appeal",
            field=models.BooleanField(
                default=True,
                help_text="Should the Appeal message be shown on the contributor portal?",
                verbose_name="Show Appeal in contributor portal",
            ),
        ),
    ]
