# Generated by Django 4.2.16 on 2024-11-13 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0026_DEV-4610_add_integrations"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organization",
            options={"verbose_name": "Organization", "verbose_name_plural": "Organizations"},
        ),
    ]
