# Generated by Django 3.2.5 on 2021-08-13 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0025_auto_20210806_1852"),
        ("organizations", "0026_rename_org_google_analytics_v4_id_revenueprogram_google_analytics_v4_id"),
    ]

    operations = []
