# Generated by Django 3.2.5 on 2021-08-13 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0022_organization_contact_email"),
        ("organizations", "0027_merge_20210813_1330"),
    ]

    operations = []
