# Generated by Django 3.2.5 on 2021-08-13 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0026_merge_20210810_1830"),
        ("organizations", "0028_merge_20210813_1630"),
    ]

    operations = []
