# Generated by Django 4.2.19 on 2025-03-04 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0028_DEV-5388_revenueprogram_activecampaign_server_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="revenueprogram",
            name="mailchimp_monthly_contributors_segment_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="revenueprogram",
            name="mailchimp_yearly_contributors_segment_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RenameField(
            model_name="revenueprogram",
            old_name="mailchimp_contributor_segment_id",
            new_name="mailchimp_one_time_contributors_segment_id",
        ),
        migrations.RenameField(
            model_name="revenueprogram",
            old_name="mailchimp_recurring_contributor_segment_id",
            new_name="mailchimp_recurring_contributors_segment_id",
        ),
    ]
