# Generated by Django 3.2.5 on 2021-08-17 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0027_revenueprogram_facebook_pixel_id"),
        ("organizations", "0029_merge_20210813_1932"),
    ]

    operations = []
