# Generated by Django 3.2.5 on 2021-08-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0029_merge_20210813_1932"),
    ]

    operations = [
        migrations.AddField(
            model_name="revenueprogram",
            name="twitter_handle",
            field=models.CharField(blank=True, help_text="How can your donors mention you on Twitter?", max_length=15),
        ),
        migrations.AddField(
            model_name="revenueprogram",
            name="website_url",
            field=models.URLField(blank=True, help_text="Does this Revenue Program have a website?"),
        ),
    ]
