# Generated by Django 3.2.5 on 2021-09-01 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0030_auto_20210826_1545"),
        ("organizations", "0030_merge_20210817_1640"),
    ]

    operations = []
