# Generated by Django 4.2.23 on 2025-08-05 20:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0030_DEV-5977_organization_disable_reminder_emails"),
    ]

    operations = [
        migrations.CreateModel(
            name="RevenueProgramContentSecurityPolicy",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        db_index=True, default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        db_index=True, default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "directive_type",
                    models.CharField(
                        choices=[
                            ("connect-src", "Connect"),
                            ("default-src", "Default"),
                            ("font-src", "Font"),
                            ("frame-src", "Frame"),
                            ("img-src", "Image"),
                            ("object-src", "Object"),
                            ("script-src", "Script"),
                            ("style-src", "Style"),
                        ],
                        max_length=20,
                    ),
                ),
                ("directive_value", models.CharField(max_length=1000)),
                (
                    "revenue_program",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="organizations.revenueprogram"),
                ),
            ],
            options={
                "unique_together": {("revenue_program", "directive_type")},
            },
        ),
    ]
