# Generated by Django 3.2.5 on 2021-09-01 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0030_auto_20210830_1732"),
        ("organizations", "0031_merge_20210901_1553"),
    ]

    operations = []
