# Generated by Django 3.2.5 on 2021-09-01 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
        ("organizations", "0032_merge_20210901_1722"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="address",
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to="common.address"),
        ),
        migrations.AddField(
            model_name="revenueprogram",
            name="address",
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to="common.address"),
        ),
    ]
