# Generated by Django 3.2.5 on 2021-09-01 17:27

from django.db import migrations


def forwards(apps, *args):
    Organization = apps.get_model("organizations", "Organization")
    Address = apps.get_model("common", "Address")
    for organization in Organization.objects.all():
        org_addr1 = organization.org_addr1
        org_addr2 = organization.org_addr2
        org_city = organization.org_city
        org_state = organization.org_state
        org_zip = organization.org_zip
        address = Address.objects.create(
            address1=org_addr1,
            address2=org_addr2,
            city=org_city,
            state=org_state,
            postal_code=org_zip,
        )
        organization.address = address
        organization.save()


def reverse(apps, *args):
    Organization = apps.get_model("organizations", "Organization")
    for organization in Organization.objects.filter(address__isnull=False):
        organization.org_addr1 = organization.address.address1
        organization.org_addr2 = organization.address.address2
        organization.org_city = organization.address.city
        organization.org_state = organization.address.state
        organization.org_zip = organization.address.postal_code
        organization.save()


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0033_auto_20210901_1726"),
    ]

    operations = [
        migrations.RunPython(forwards, reverse),
    ]
