# Generated by Django 3.2.5 on 2021-09-01 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0034_auto_20210901_1727"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="org_addr1",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="org_addr2",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="org_city",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="org_state",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="org_zip",
        ),
    ]
