# Generated by Django 3.2.5 on 2021-09-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0035_auto_20210901_1729"),
    ]

    operations = [
        migrations.AlterField(
            model_name="revenueprogram",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="This will be used as the subdomain for donation pages made under this revenue program",
                max_length=63,
                unique=True,
            ),
        ),
    ]
