# Generated by Django 3.2.5 on 2021-10-05 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0003_auto_20211005_1324"),
        ("organizations", "0036_revenueprogram_social_meta"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="currency",
            field=models.CharField(choices=[("USD", "USD"), ("CAD", "CAD")], default="USD", max_length=3),
        ),
        migrations.AlterField(
            model_name="organization",
            name="address",
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="common.address"),
        ),
    ]
