# Generated by Django 3.2.5 on 2021-10-01 18:47

import apps.organizations.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0036_revenueprogram_stripe_statement_descriptor_suffix"),
    ]

    operations = [
        migrations.AlterField(
            model_name="revenueprogram",
            name="stripe_statement_descriptor_suffix",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                validators=[apps.organizations.validators.validate_statement_descriptor_suffix],
            ),
        ),
    ]
