# Generated by Django 3.2.5 on 2021-10-01 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0036_revenueprogram_social_meta"),
        ("organizations", "0037_alter_revenueprogram_stripe_statement_descriptor_suffix"),
    ]

    operations = []
