# Generated by Django 3.2.5 on 2021-10-05 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0036_alter_revenueprogram_slug"),
        ("organizations", "0038_merge_20211001_1852"),
    ]

    operations = []
