# Generated by Django 3.2.5 on 2021-10-06 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0037_auto_20211005_1324"),
        ("organizations", "0039_merge_20211005_1855"),
    ]

    operations = []
