# Generated by Django 3.2.5 on 2021-10-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0040_merge_20211006_1423"),
    ]

    operations = [
        migrations.AddField(
            model_name="revenueprogram",
            name="allow_offer_nyt_comp",
            field=models.BooleanField(
                default=False,
                help_text="Should page authors for this Revenue Program see the option to offer their donors a comp subscription to the New York Times?",
                verbose_name="Allow page editors to offer an NYT subscription",
            ),
        ),
    ]
