# Generated by Django 3.2.5 on 2021-11-30 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0041_revenueprogram_allow_offer_nyt_comp"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="stripe_oauth_refresh_token",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
