# Generated by Django 3.2.5 on 2022-01-28 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0042_organization_stripe_oauth_refresh_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="slug",
        ),
    ]
