# Generated by Django 3.2.5 on 2022-01-27 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0035_merge_0034_alter_font_options_0034_auto_20220110_1845"),
        ("organizations", "0042_organization_stripe_oauth_refresh_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="revenueprogram",
            name="default_donation_page",
            field=models.ForeignKey(
                blank=True,
                help_text="Choose an optional default donation page once you've saved your initial revenue program",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pages.donationpage",
            ),
        ),
    ]
