# Generated by Django 3.2.5 on 2022-02-03 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0043_alter_revenueprogram_default_donation_page"),
        ("organizations", "0045_alter_revenueprogram_slug"),
    ]

    operations = []
