# Generated by Django 3.2.5 on 2022-02-17 21:41

import apps.config.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0046_merge_20220203_1437"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=63, validators=[apps.config.validators.validate_slug_against_denylist]
            ),
        ),
    ]
