# Generated by Django 3.2.5 on 2022-02-17 21:42

from django.db import migrations

from apps.common.utils import normalize_slug


def forwards(apps, *args):
    org_model = apps.get_model("organizations", "Organization")

    for org in org_model.objects.all():
        org.slug = normalize_slug(name=org.name)
        org.save()


def reverse(apps, *args):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0047_organization_slug"),
    ]

    operations = [
        migrations.RunPython(forwards, reverse),
    ]
