# Generated by Django 3.2.5 on 2022-02-17 21:43

import apps.config.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0048_auto_20220217_2142"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="slug",
            field=models.SlugField(
                max_length=63, unique=True, validators=[apps.config.validators.validate_slug_against_denylist]
            ),
        ),
    ]
