# Generated by Django 3.2.5 on 2022-02-23 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0048_initial_historical_record"),
        ("organizations", "0049_alter_organization_slug"),
    ]

    operations = []
