# Generated by Django 3.2.5 on 2022-02-23 14:33

import apps.config.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0050_merge_20220223_1432"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalorganization",
            name="slug",
            field=models.SlugField(
                default="temp-historical",
                max_length=63,
                validators=[apps.config.validators.validate_slug_against_denylist],
            ),
            preserve_default=False,
        ),
    ]
