# Generated by Django 3.2.5 on 2022-05-09 19:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0051_historicalorganization_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentProvider",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        db_index=True, default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        db_index=True, default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("stripe_account_id", models.CharField(max_length=255, unique=True)),
                ("stripe_product_id", models.CharField(blank=True, max_length=255)),
                ("currency", models.CharField(choices=[("USD", "USD"), ("CAD", "CAD")], default="USD", max_length=3)),
                (
                    "default_payment_provider",
                    models.CharField(choices=[("stripe", "Stripe")], default="stripe", max_length=100),
                ),
                ("stripe_oauth_refresh_token", models.CharField(blank=True, max_length=255)),
                (
                    "stripe_verified",
                    models.BooleanField(
                        default=False,
                        help_text='A fully verified Stripe Connected account should have "charges_enabled: true" in Stripe',
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="historicalorganization",
            name="currency",
        ),
        migrations.RemoveField(
            model_name="historicalorganization",
            name="default_payment_provider",
        ),
        migrations.RemoveField(
            model_name="historicalorganization",
            name="domain_apple_verified_date",
        ),
        migrations.RemoveField(
            model_name="historicalorganization",
            name="non_profit",
        ),
        migrations.RemoveField(
            model_name="historicalorganization",
            name="stripe_account_id",
        ),
        migrations.RemoveField(
            model_name="historicalorganization",
            name="stripe_oauth_refresh_token",
        ),
        migrations.RemoveField(
            model_name="historicalorganization",
            name="stripe_product_id",
        ),
        migrations.RemoveField(
            model_name="historicalorganization",
            name="stripe_verified",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="currency",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="default_payment_provider",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="domain_apple_verified_date",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="non_profit",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="stripe_account_id",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="stripe_oauth_refresh_token",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="stripe_product_id",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="stripe_verified",
        ),
        migrations.AddField(
            model_name="historicalrevenueprogram",
            name="domain_apple_verified_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalrevenueprogram",
            name="non_profit",
            field=models.BooleanField(default=True, verbose_name="Non-profit?"),
        ),
        migrations.AddField(
            model_name="revenueprogram",
            name="domain_apple_verified_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="revenueprogram",
            name="non_profit",
            field=models.BooleanField(default=True, verbose_name="Non-profit?"),
        ),
        migrations.AddField(
            model_name="historicalrevenueprogram",
            name="payment_provider",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="organizations.paymentprovider",
            ),
        ),
        migrations.AddField(
            model_name="revenueprogram",
            name="payment_provider",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="organizations.paymentprovider"
            ),
        ),
    ]
