# Generated by Django 3.2.13 on 2022-05-06 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0051_historicalorganization_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalorganization",
            name="uses_email_templates",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="uses_email_templates",
        ),
    ]
