# Generated by Django 3.2.5 on 2022-03-31 18:19

from django.db import migrations, models
import django.db.models.deletion


def update_benefits():
    pass


def update_benefit_level():
    pass


def update_benefit_level_with_revenue_program(apps, rp_with_org):
    benefit_level_model = apps.get_model("organizations", "BenefitLevel")
    for benefit_level in benefit_level_model.objects.all():
        benefit_level.revenue_program_id = rp_with_org[benefit_level.organization.id]
        benefit_level.save()


def forwards(apps, *args):
    rp_model = apps.get_model("organizations", "RevenueProgram")
    org_with_rp = {
        i["organization_id"]: i["id"]
        for i in rp_model.objects.distinct("organization_id")
        .order_by("organization_id", "created")
        .values("id", "organization_id", "revenueprogrambenefitlevel")
    }
    update_benefit_level_with_revenue_program(apps, org_with_rp)
    # rp_benefit_level_model = apps.get_model("organizations", "RevenueProgramBenefitLevel")
    # benefit_model = apps.get_model("organizations", "Benefit")
    # benefit_level_model = apps.get_model("organizations", "BenefitLevel")

    # for benefit in benefit_model.objects.all():
    #     benefit.revenue_program_id = org_to_rp_map_values[benefit.organization_id]


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0051_historicalorganization_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="benefitlevel",
            options={"ordering": ("level",)},
        ),
        migrations.AddField(
            model_name="benefit",
            name="revenue_program",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="organizations.revenueprogram"
            ),
        ),
        migrations.AddField(
            model_name="benefitlevel",
            name="level",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="Is this a first-level benefit, second-level, etc?"
            ),
        ),
        migrations.AddField(
            model_name="benefitlevel",
            name="revenue_program",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="organizations.revenueprogram"
            ),
        ),
        migrations.RunPython(forwards),
        migrations.AddField(
            model_name="historicalbenefit",
            name="revenue_program",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="organizations.revenueprogram",
            ),
        ),
        migrations.AddField(
            model_name="historicalbenefitlevel",
            name="level",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="Is this a first-level benefit, second-level, etc?"
            ),
        ),
        migrations.AddField(
            model_name="historicalbenefitlevel",
            name="revenue_program",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="organizations.revenueprogram",
            ),
        ),
    ]
