# Generated by Django 3.2.13 on 2022-06-15 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0052_map_benefits_and_levels_to_rp_not_org"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalbenefitlevel",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalbenefitlevel",
            name="revenue_program",
        ),
        migrations.RemoveField(
            model_name="historicalfeature",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalorganization",
            name="address",
        ),
        migrations.RemoveField(
            model_name="historicalorganization",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalorganization",
            name="plan",
        ),
        migrations.RemoveField(
            model_name="historicalplan",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalrevenueprogram",
            name="address",
        ),
        migrations.RemoveField(
            model_name="historicalrevenueprogram",
            name="default_donation_page",
        ),
        migrations.RemoveField(
            model_name="historicalrevenueprogram",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalrevenueprogram",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="historicalrevenueprogram",
            name="social_meta",
        ),
        migrations.DeleteModel(
            name="HistoricalBenefit",
        ),
        migrations.DeleteModel(
            name="HistoricalBenefitLevel",
        ),
        migrations.DeleteModel(
            name="HistoricalFeature",
        ),
        migrations.DeleteModel(
            name="HistoricalOrganization",
        ),
        migrations.DeleteModel(
            name="HistoricalPlan",
        ),
        migrations.DeleteModel(
            name="HistoricalRevenueProgram",
        ),
    ]
