name: tests

on:
  push:
    branches:
      - '!*skipcy*'

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress tests
        uses: cypress-io/github-action@v2
        with:
          working-directory: spa
          build: npx cypress info
          start: npm run start
          wait-on: http://localhost:3000
          browser: chrome
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: spa/cypress/screenshots
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-videos
          path: spa/cypress/videos