name: Setup Python Environment

on:
  workflow_call:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code so the workflow has access to the repository
      - uses: actions/checkout@v4

      # Set up the correct Python version
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # Cache the dependencies to speed up future builds
      - name: Cache Python dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: python-deps-${{ runner.os }}-${{ hashFiles('**/pyproject.toml', '**/uv.lock') }}
          restore-keys: |
            python-deps-${{ runner.os }}-

      # Install uv
      - name: Install uv
        run: pip install uv

      # Sync dependencies with uv
      - name: Sync dependencies with uv
        run: uv sync
