name: Build and Test React Application

on:
  push:
    branches:
      - "*"
jobs:
  js-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install node dependencies, build and test
        run: |
          cd spa
          npm ci
          npm run test:ci

  cypress-test:
    runs-on: ubuntu-latest
    strategy:
      # when one test fails, DO NOT cancel the other
      # containers, because this will kill Cypress processes
      # leaving the Dashboard hanging ...
      # https://github.com/cypress-io/github-action/issues/48
      fail-fast: false
      matrix:
        # run 3 copies of the current job in parallel
        containers: [1, 2, 3]
    env:
      REACT_APP_HUB_STRIPE_API_PUB_KEY: pk_test_djfoi12312414
      REACT_APP_STRIPE_ACCOUNT_ID: acc_3kjfo23jj
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup custom hosts for subdomain testing
        run: |
          echo "127.0.0.1 revengine-testabc123.com" | sudo tee -a /etc/hosts
          echo "127.0.0.1 revenueprogram.revengine-testabc123.com" | sudo tee -a /etc/hosts
      - name: Debug hosts
        run: cat /etc/hosts
      - name: Cypress tests
        uses: cypress-io/github-action@v4
        with:
          working-directory: spa
          build: npx cypress info
          start: npm run start:subdomains
          wait-on: http://localhost:3000
          # because of "record" and "parallel" parameters
          # these containers will load balance all found tests among themselves
          record: true
          parallel: true
          group: "Cypress integration tests"
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_PROJECT_ID: ${{ secrets.PROJECT_ID }}
