name: Build and Test Python

on:
  pull_request:
  push:
    branches: [main, develop]

jobs:
  # Only run if Django code has changed
  check-changes:
    runs-on: ubuntu-latest
    # Required permissions
    permissions:
      pull-requests: read
    # Set job outputs to values from filter step
    outputs:
      django: ${{ steps.filter.outputs.django }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            django:
              - 'apps/**'
              - 'public/**'
              - 'revengine/**'
              - 'conftest.py'
              - 'manage.py'
              - 'poetry.lock'
              - 'pyproject.toml'
              - 'pytest.ini'

  setup-python:
    uses: ./.github/workflows/setup-python.yml
    needs: check-changes
  test_python:
    needs: check-changes
    if: ${{ needs['check-changes'].outputs.django == 'true' }}
    runs-on: ubuntu-latest
    services:
      postgres:
        # From:
        # https://docs.github.com/en/actions/guides/creating-postgresql-service-containers
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download python build artifact
        uses: actions/download-artifact@v3
        with:
          name: python-venv
          path: .venv

      - name: Run tests
        run: source .venv/bin/activate && make run-tests
        env:
          DJANGO_SETTINGS_MODULE: revengine.settings.dev
          DATABASE_URL: postgres://postgres:postgres@127.0.0.1:5432/postgres
          GS_CREDENTIALS_RAISE_ERROR_IF_UNSET: "false"
          # need to add the virtual environment to the path and ensure make command is available
          PATH: /usr/bin:/usr/local/bin:/bin:/venv/bin:$PATH
