name: Build and Test React Application

on:
  push:
    branches:
      - '*'
      - '!*skipcy*'

jobs:
  js-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
      - name: Install node dependencies, build and test
        run: |
          cd spa
          npm ci
          npm run test:ci

  cypress-test:
    runs-on: ubuntu-latest
    env:
      REACT_APP_HUB_STRIPE_API_PUB_KEY: pk_test_31XWC5qhlLi9UkV1OzsI634W
      REACT_APP_STRIPE_ACCOUNT_ID: acct_1ASCSHBMAMOLTEak
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup custom hosts for subdomain testing
        run: |
          echo "127.0.0.1 revengine-testabc123.com" | sudo tee -a /etc/hosts
          echo "127.0.0.1 revenueprogram.revengine-testabc123.com" | sudo tee -a /etc/hosts
      - name: Debug hosts
        run: cat /etc/hosts
      - name: Cypress tests
        uses: cypress-io/github-action@v2
        with:
          working-directory: spa
          build: npx cypress info
          start: npm run start:subdomains
          wait-on: http://localhost:3000
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: spa/cypress/screenshots
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-videos
          path: spa/cypress/videos
